### PR TITLE
[Draft]throw exception for fallback

### PR DESCRIPTION
**Pull request by xieofxie**
##  Description

- throw exception for fallback: for better debugging. Should we make it an option?

## Specific Changes

  - throw NotImplementedException in handler.Fallback.Respond

## Testing

update TestScriptTests_HttpRequestMock.test.dialog for fallback

### CODE REVIEW

**Comment by cleemullins** [comment]
Please create an issue that has all the details in it. This PR should fix that issue.

**Comment by cleemullins** [comment]
This seems strongly related to #4212 and #4201. Can you please create a detailed issue describing the overall problem, and then link each PR to that issue so we can track.

**Comment by xieofxie** [comment]
Hi @cleemullins I encountered an issue for the second feature 'throw exception for fallback' https://github.com/microsoft/botbuilder-dotnet/issues/4186
So I create this pr https://github.com/microsoft/botbuilder-dotnet/pull/4199 for the first feature 'use new HttpContent each time'

And once that issue #4186 is resolved, I will change this for the first feature.

Thanks

**Comment by xieofxie** [comment]
Now even windows begin to stackoverflow..

**Comment by cleemullins** [comment]
Close this PR due to inactivity. @xieofxie please re-open if it's still relevant.

**Pull request closed without merging**
