### PR TITLE
change to start <= line <= end

### PR DESCRIPTION
**Pull request by xieofxie**
Will the extension be open sourced?

### CODE REVIEW

**Comment by xieofxie** [comment]
Possible related for PR check? https://github.com/dotnet/corefx/issues/38966

**Comment by willportnoy** [comment]
@xieofxie the change looks reasonable - can you give an example from the current code where the breakpoint resolves to the wrong item?  I’m concerned this PR will tighten breakpoint resolution enough that the user will be confused.

**Comment by willportnoy** [comment]
@xieofxie the Dialog Debugger VSCode Extension was added in this commit https://github.com/microsoft/botbuilder-tools/commit/2d6170084ead8ba1e1a84a0095e29397f060e64f but removed in this commit https://github.com/microsoft/botbuilder-tools/commit/7cbcc4814b63f319ce8527b47900c4a40c1d8dfb - @chrimc62 @tomlm is there a new home for Dialog Debugger VSCode Extension?

**Comment by xieofxie** [comment]
@willportnoy Currently if one clicks inside the brackets {} (e.g. an action), it will set a breakpoint in the brackets below.

As far as dialog file is well formed, a closed range may not harm.

**Pull request merged**
