### PR TITLE
Show lower scoring intents, as well as top intent, on bot context

### PR DESCRIPTION
**Pull request by garypretty**
@cleemullins This isn't necessarily ready to merge yet - but wanted to run this past you and get your opinion on it along with a couple of further options.  Through the use of the IntentRecognizerMiddleware we are currently hiding all but the top intent returned.  In my experience there are many cases where it is useful for the developer to see the lower scoring intents as well as the top one - in order to check if there are other close matches for example.  This PR adds an Intents property to the context so that the developer will have access to both the top and all intents returned.

So, a couple of questions;

1. Are you happy with the principle of making the other intents visible?

2. I considered making the TopIntent property on the context read only and calculating it based on the intents list (i.e. move the method FindTopIntent from the IntentRecognizerMiddleware to the context). What are your thoughts?

cc @daltskin for thoughts.

### CODE REVIEW

**Comment by garypretty** [comment]
@cleemullins I will obviously add / update tests as appropriate once we have agreed the approach.

**Comment by cleemullins** [comment]
This is a good example of where we need more clairty in our Roadmap. My fault. 

The intent (ahem!), and this is already done on the Node side, is to remove the Intent plumbing from BotContext and have it added in by specific intent-related middleware components. That methods like TopIntent are on BotContext is something I feel bad about, as I haven't caught up to Steve in removing them. 

The goal(s) here is to dramatically simplify Context. 

If I may, **Please!** particpate in the ongoing discussion here, as we would really love some additional perspectives. 
(Context) https://github.com/Microsoft/botbuilder-js/issues/66
(Middleware Pipelines) https://github.com/Microsoft/botbuilder-js/issues/74

**Comment by garypretty** [comment]
Great, thanks for the clarity here Chris. I suspected this might be the case, hence me just putting a quick idea together. I'll absolutely feed into those conversations and if I can help implement some of these changes on the .net side then I am more than happy too.

**Comment by garypretty** [comment]
Closing this for now. I will feed into the Intent bits as the middleware / context picture becomes clearer over the coming days / weeks.

**Pull request closed without merging**
