### PR TITLE
Surface LG CacheScope out in LG file options

### LINKED ISSUE #4965: Surface LG CacheScope out in LG file options for Composer
### Context
During the perf investigation for Meeting Assistant, to help get the best performance, we developed (
https://github.com/microsoft/botbuilder-dotnet/pull/4602) a new and more aggressive cache policy called scope = global, in which we will try to cache as much evaluation result as possible. 

So current there are three LG cache scopes(global/local/none) can be chose when calling LG evaluation API. 
```c#
// pseudo code
var result = templates.Evaluate(...., new LGEvaluationOptions {cacheScope = global/local/none}) 
```

### Issue
The issue is this cache scope (policy) is not configurable via Composer. Composer will use the default scope "locale". Then scenarios like Meeting Assistant aren't getting the best performance they are looking for. 

### Proposed solution
Surface this cacheScope out, like many other options before, via the options section (https://docs.microsoft.com/en-us/azure/bot-service/file-format/bot-builder-lg-file-format?view=azure-bot-service-4.0#options) inside lg file.

### Details

Support the following options in LG file to specify the cache scope
```
> !# @cacheScope= global/local/none   // by default is local
```

### PR DESCRIPTION
**Pull request by Danieladu**
Fixes #4965 

## Description

Support the following options in LG file to specify the cache scope
```
> !# @cacheScope= global/local/none   // by default is local
```

###  Support setting LG  cache scope in LG file
```
> !# @cacheScope= global // global cache
> !# @cacheScope= local // local cache
> !# @cacheScope= none // none cache
> !# @cacheScope= xxx // fallback to local cache
```

### Global cache is effective in the life cycle of an evaluation
For example:
```
var templates = Templates.ParseFile("xxx.lg");
var result1 = templates.Evaluate("template", null, new EvaluationOptions { CacheScope = LGCacheScope.Global});

// The second evaluation would drop all the results cached before.
var result2 = templates.Evaluate("template", null, new EvaluationOptions { CacheScope = LGCacheScope.Global});
```

### Option name case insensitive
```
> !# @cacheScope= global // ok
> !# @CACHESCOPE= global // ok
> !# @cachescope= global // ok
...
```

### Cache scope would follow the scope of the entrance LG
For example:
a.lg:
```
> !# @cacheScope= global
 [import](b.lg)

```

b.lg
```
> !# @cacheScope= none
# template1
- ${template2()} ${template2()}

# template2
- ${rand(1, 10000000)}
```
Code:
```
var templates = Templates.ParseFile("a.lg");
var result = templates.Evaluate("template1"); // the second "template2" would use the cache of the first evaluate result
```

### CODE REVIEW

**Comment by boydc2014** [comment]
@Danieladu  will the value of the cache scope case insensitive?

**Comment by Danieladu** [comment]
> @Danieladu will the value of the cache scope case insensitive?

Yes. The key/value of cache scope are all case insensitive.

**Review by boydc2014 — APPROVED** [review]

**Comment by boydc2014** [comment]
LGTM, please note we need to open an ticket for this in docs repo to update the doc.

**Review by mrivera-ms — APPROVED** [review]

**Pull request merged**
