### PR TITLE
Prevent Cortana from trying to use suggested actions in prompts (#1173)

### LINKED ISSUE #1173: Cortana bots try to use suggested actions
## Version
4.1.5

## Describe the bug
It is known that Cortana does not support suggested actions, but there is logic in [`ChoiceFactory.ForChannel`](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Choices/ChoiceFactory.cs#L36) that directs a Cortana bot to use suggested actions when a `ChoicePrompt` is set to the default list style of `ListStyle.Auto`. I do not know the reasoning behind this. In the line `if (!longTitles && (supportsSuggestedActions || (!hasMessageFeed && supportsCardActions)))`, Cortana satisfies that condition because even though it [doesn't support suggested actions](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Choices/Channel.cs#L10) it [does support card actions](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Choices/Channel.cs#L46) and also [doesn't have a message feed](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Choices/Channel.cs#L54). At least one customer has run into [issues](https://github.com/Microsoft/botbuilder-dotnet/issues/1098) because of this.

## To Reproduce
1. Create a bot with a `ChoicePrompt` without specifying a list style so that it defaults to "auto"
2. Connect the bot to Cortana
3. Run the bot and send messages to it
4. Observe that the choices are not displayed in any form (text, buttons, or suggested actions)

## Expected behavior
The desired behavior would be for the choices to be displayed as [buttons](https://github.com/Microsoft/botbuilder-dotnet/issues/1170), but failing that they should at least be displayed as text.

## Screenshots
A screenshot of the behavior can be found [here](https://github.com/Microsoft/botbuilder-dotnet/issues/1098#issuecomment-437997427).

## Additional context
I am happy to fix this myself if that's acceptable.

[bug]

### PR DESCRIPTION
**Pull request by v-kydela**
I have modified ChoiceFactory.cs by removing `hasMessageFeed` and `supportsCardActions` from the `if` condition so that now a channel _must_ support suggested actions in order for the SDK to automatically select them as the list style. I have also deleted those local variables for cleanliness since they aren't being used anywhere else.

Fixes #1173

### CODE REVIEW

**Comment by Stevenic** [comment]
There is an issue here but the issue appears to be that we're not generating a Card with buttons for Cortana. Could you please file an issue for this as the same issue exists on both JS and C#.

**Comment by cleemullins** [comment]
@v-kydela Can you add the test, per @stevengum at which point we can merge.

**Comment by v-kydela** [comment]
@cleemullins - Yes, I am working on it now.

@Stevenic - The issue exists and has been triaged for 4.4: https://github.com/Microsoft/botbuilder-dotnet/issues/1170

**Comment by v-kydela** [comment]
@cleemullins 
@stevengum 

I have included a test for Cortana in ChoiceFactoryTests.cs and modified the Emulator test to use the channel name constant for consistency.

**Comment by stevengum** [comment]
@v-kydela, @cleemullins the [build](https://fuselabs.visualstudio.com/86659c66-c9df-418a-a371-7de7aed35064/_build/results?buildId=47951) is failing due to some missing files?

@v-kydela I don't _think_ any of the latest changes in master removed these files, can you pull master in case it fixes this build break? (You'll have to merge in master eventually so why not now? 😄 )

**Comment by v-kydela** [comment]
@stevengum - I just pulled master locally, but I don't know how that would affect things. Are you saying I should merge my branch into master locally?

**Comment by v-kydela** [comment]
@garypretty - Thank you very much!

I agree that Cortana should default to hero cards whereas this PR would make Cortana default to inline or list. I made this PR thinking your fix wouldn't be until 4.4, and now that we've gotten it sooner I'm wondering what should be done with this PR. Should we drop it or amend it or what? In any case, I still don't know what to do about #4.2.0.244 failing.

**Comment by cleemullins** [comment]
This build error is very odd. I'll track it down today. Seems unrelated to this commit.

**Comment by garypretty** [comment]
@Stevenic @cleemullins @v-kydela I think my PR will supersede this one - I have added the ability to use cards, but also updated the ChoiceFactory.ForChannel to ensure that Cortana will default to cards instead of suggested actions.

**Comment by v-kydela** [comment]
@garypretty - If we're going to drop this pull request in favor of yours then I think your PR should include a test that verifies that Cortana does not use suggested actions.

**Comment by garypretty** [comment]
@v-kydela Agreed - good catch - I have updated my PR to include tests for both Teams and Cortana to ensure the correct card is presented.

**Comment by cleemullins** [comment]
@v-kydela Can you resolve the conficts in the code? I'm working on the build now.

**Comment by garypretty** [comment]
@cleemullins this PR should be closed I believe. I've included these changes in my PR which was accepted list night.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request closed without merging**
