### PR TITLE
Adding new stand alone samples for bot translator 

### PR DESCRIPTION
**Pull request by amr-elsehemy**
- Added new LUIS translator sample
-Added new QnA translator sample

### CODE REVIEW

**Comment by cleemullins** [comment]
@amirt-microsoft Please enable StyleCop.Analyzers and AsyncUsageAnalyzers. Please also use the BotBuilder.Ruleset file, so that we are enforcing the same rules across all projects. You can look at any of the BotBuilder projects to see how this is setup and enabled. 

We are working now on adding them to the samples. 

Once you've got all the StyleCop related warnings cleaned up, I'm happy to review this PR.

**Comment by cleemullins** [comment]
@amr-elsehemy To enable, add the following to your solution file:
```
<ItemGroup>
		<PackageReference Include="AsyncUsageAnalyzers" Version="1.0.0-alpha003" PrivateAssets="all" />
		<PackageReference Include="StyleCop.Analyzers" Version="1.1.0-beta008" PrivateAssets="all" />
	</ItemGroup>
```

The ruleset file we're using you should simply copy for now ("Botbuilder.Ruleset"). I'll soon package this up in a NuGet package and add it as a dependency across the system, but we're not quite ready for that yet.

**Comment by amr-elsehemy** [comment]
@cleemullins I've a concern regarding the `OnTurn` method in `IBot ` interface, it seems that the method naming to `OnTurnAsync` is not available in the current Bot builder nuget package, so I can't quiet rename that in the sample to resolve AsyncUsageAnalyzers warning , so what's the current convention to address that ?

**Comment by cleemullins** [comment]
@amr-elsehemy Hey Amir, the OnTurnAsync has been renamed in the master repo, but the correstponding packages have NOT yet been published to the Nuget feed. As you point out, the samples in the Repo are based on our public Nuget packages, creating a chicken/egg problem. 

The answer for now is "queue up the changes" and we'll update the samples the day after the new packages are published.

**Comment by cleemullins** [comment]
@amr-elsehemy The folks from Southworks have updated the Translation code to the latest APIs and applied a majority of the stylecop rules. Can you take a look at that and see what impact, if any, there is on this code?

**Comment by cleemullins** [comment]
The Translation components have been removed from the product for the time being and are being moved to a sample. Closing this PR.

**Pull request closed without merging**
