### PR TITLE
changed Dictionary to be case insensitive by passing in case insensitive StringComparer

### PR DESCRIPTION
**Pull request by som-nitjsr**
will use .ToLower() to avoid the Key not found exception at   var defaults = ChoiceDefaults[culture];
          
line no  104
System.Collections.Generic.Dictionary`2.get_Item(TKey key)

### CODE REVIEW

**Comment by tomlm** [comment]
>         private static readonly Dictionary<string, (Choice, Choice, ChoiceFactoryOptions)> ChoiceDefaults = new Dictionary<string, (Choice, Choice, ChoiceFactoryOptions)>()

Better solution would be to change Dictionary to be case insensitive by passing in case insensitive StringComparer.

---
Refers to: libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ConfirmInput.cs:20 in 48e8de8. [](commit_id = 48e8de8c78f15c4d194d92eb060b32c56351ee5e, deletion_comment = False)

**Comment by som-nitjsr** [comment]
I have addressed the review comments

**Comment by som-nitjsr** [comment]
Is there is any missing to get this PR merged?

**Comment by som-nitjsr** [comment]
@tomlm let me know if i need to do any thing more.

**Pull request merged**
