### PR TITLE
Fix OAuth bug

### LINKED ISSUE #3663: OAuthInput does not work in Composer since it requires alwaysPrompt field not null.
## Version
master

## Describe the bug
This issue is reported from composer side. 
https://github.com/microsoft/BotFramework-Composer/issues/2477

Two issues:
1. OAuthInput requires alwaysPrompt not null in code.
2. in the OAuthInput schema file alwaysPrompt is missing. 

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

### PR DESCRIPTION
**Pull request by luhan2017**
fixes #3663

### CODE REVIEW

**Comment by vishwacsena** [comment]
@luhan2017 apart from the component schema, we also need to rev the sdk.schema under schemas folder.

**Comment by luhan2017** [comment]
> @luhan2017 apart from the component schema, we also need to rev the sdk.schema under schemas folder.

Good catch, sdk.schema updated

**Comment by cleemullins** [comment]
@tomlm, this is the PR that fixes a blocking P0 bug. Please review, and provide feedback ASAP.

**Comment by luhan2017** [comment]
@vishwacsena and @tomlm, this is a blocking issue for composer for R9, please help review.

**Pull request merged**
