### PR TITLE
Add VSIX project template with EchoBot sample

### PR DESCRIPTION
**Pull request by enzocanoo**
This pull-request adds `EchoBot.Template` project to `Microsoft.Bot.Builder` solution. The VSIX project includes a template with the latest version of `AspNetCore-EchoBot-With-State`.

Note: To tests the template, just build the project and install the `EchoBot.Template.vsix` generated in the output directory.

### CODE REVIEW

**Comment by cleemullins** [comment]
I would like to hold-off merging this until Tuesday (Monday is a holiday). My concerns are around how we can setup the automated build for this so it automatically pushes to the VSIX feed on botbuilder.myget.org.

**Comment by enzocanoo** [comment]
Hi @cleemullins, we added a new script that:
- Update the VSIX installer version using `env:new_version` environment variable.
- Generate the .zip file with the template.
- Build the VSIX project and generate the installer.
- Sign the new installer using a valid `certificate.pfx` file and `env:templates_sign` with the corresponding password.
- Upload the VSIX installer to MyGet using the authToken in `env:myget_key`.

**Comment by enzocanoo** [comment]
@cleemullins, we deleted the .zip file and added a `PreBuildEvent` to generate it using PowerShell.

**Comment by cleemullins** [comment]
This has been depricated in favor of adding it to the Samples repo:
https://github.com/Microsoft/BotBuilder-Samples/tree/v4/generators/vsix-vs-win/BotBuilderVSIX-V4

**Pull request closed without merging**
