### PR TITLE
Fix DialogStateMamager TryGetValue method  throwing FormatException

### PR DESCRIPTION
**Pull request by cosmicshuai**
fixes: #4464

### CODE REVIEW

**Review by boydc2014 — APPROVED** [review]

**Comment by boydc2014** [comment]
Looks good to me, @tomlm, can you confirm?

**Comment by tdurnford** [comment]
@cosmicshuai Can you please resolve the conflicts so we can get this change merged in?

@tomlm Can you leave a review as well?

**Comment by cosmicshuai** [comment]
> @cosmicshuai Can you please resolve the conflicts so we can get this change merged in?
> 
> @tomlm Can you leave a review as well?

@tdurnford Sorry for the late. Didn't noticed the conflict. I just resolved it.

**Review by tomlm — APPROVED** [review]
:shipit:

**Comment by mrivera-ms** [comment]
@gabog , @johnataylor , could one of you please review? Thank you.

**Review by axelsrz — APPROVED** [review]

**Pull request merged**
