### PR TITLE
Try to fix event emit order

### LINKED ISSUE #4817: Custom Action Events arrive in wrong order
When emitting events from a custom action, they arrive in the wrong order;

image
image
image

```
namespace Microsoft.BotFramework.Composer.CustomAction
{
    public class EventEmitter : Dialog
    {
        [JsonConstructor]
        public EventEmitter([CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0)
            : base()
        {
            this.RegisterSourceLocation(sourceFilePath, sourceLineNumber);
        }

        [JsonProperty("$kind")]
        public const string Kind = "EventEmitter";

        public async override Task<DialogTurnResult> BeginDialogAsync(DialogContext dialogContext, object options = null, CancellationToken cancellationToken = default(CancellationToken))
        {
            await dialogContext.EmitEventAsync("Event1", null);
            await dialogContext.EmitEventAsync("Event2", null);

            return await dialogContext.EndDialogAsync();
        }
    }
}
```

### PR DESCRIPTION
**Pull request by Danieladu**
Try to fix #4817

## Description
Change the DialogEvent change type of ActionChange from "insert" policy to "append" policy.

### CODE REVIEW

**Comment by chrimc62** [comment]
Where are the tests?

**Review by chrimc62 — CHANGES_REQUESTED** [review]
:clock1:

**Comment by Danieladu** [comment]
> Where are the tests?

This bug is triggered by a custom action. Currently, I found no test about this area.
Here I just prompt a possible solution that may solve this issue and I would continue investigating the issue.

**Comment by boydc2014** [comment]
> > Where are the tests?
> 
> This bug is triggered by a custom action. Currently, I found no test about this area.
> Here I just prompt a possible solution that may solve this issue and I would continue investigating the issue.

I think it's possible that use two EmitEvent actions to simulate this, right?

**Comment by Danieladu** [comment]
> > > Where are the tests?
> > 
> > 
> > This bug is triggered by a custom action. Currently, I found no test about this area.
> > Here I just prompt a possible solution that may solve this issue and I would continue investigating the issue.
> 
> I think it's possible that use two EmitEvent actions to simulate this, right?
No. With two EmitEvent actions is totally different. That works well for the order issue.

**Comment by EricDahlvang** [comment]
Please try this repro: 
https://github.com/microsoft/botbuilder-dotnet/issues/4817#issuecomment-716170719

The processing of dialogs triggered from custom events seems to come last, after the rest of entire dialog stack completes, and in the incorrect order.  These two issues might be related, they might not.  I tried to step through this code, which processes dialog events, but it is a bit difficult to follow.

**Comment by Danieladu** [comment]
> Please try this repro:
> [#4817 (comment)](https://github.com/microsoft/botbuilder-dotnet/issues/4817#issuecomment-716170719)
> 
> The processing of dialogs triggered from custom events seems to come last, after the rest of entire dialog stack completes, and in the incorrect order. These two issues might be related, they might not. I tried to step through this code, which processes dialog events, but it is a bit difficult to follow.

Yes. Maybe that's by design. The Event would be handled at the `EndDialogAsync` stage after all other normal actions are done.
@tomlm are you aware of this one?

So the expected result of the sample is:
```
After Event 1, before Event2
After Event 2
Event1
Event2
```

But the current output is 
```
After Event 1, before Event2
After Event 2
Event2
Event1
```

If the `EmitEvent` operator should be `sync` with other actions, and the result should be:
```
Event1
After Event 1, before Event2
Event2
After Event 2
```
that would be another design DCR/or issue.

**Comment by Danieladu** [comment]
Close it temporarily for this solution is not the right way to solve this issue.

**Pull request closed without merging**
