### PR TITLE
[#5713] Dialogs.Declarative.Tests hang and give no message.

### LINKED ISSUE #5713: Dialogs.Declarative.Tests hang and give no message.
Running all tests on a new computer in Visual Studio, the tests hang indefinitely here:
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.3+1b45f5407b (64-bit .NET Core 4.6.30015.01)
[xUnit.net 00:00:03.36]   Starting:    Microsoft.Bot.Builder.Dialogs.Declarative.Tests

No message is given.

The cause: BF CLI was not installed.

Per Eric Dahlvang, the tests used to install BF CLI on the fly.
Related issues:
	https://github.com/microsoft/botbuilder-dotnet/issues/4492
	https://github.com/microsoft/botframework-sdk/issues/6226

Suggested fix: 

1. A test be added that runs before the Dialogs.Declarative.Tests that fails if the prerequisite BF CLI is not installed.

2. Set a timeout for Dialogs.Declarative.Tests at 60 seconds. (This normally completes after 20 seconds.)

### PR DESCRIPTION
**Pull request by sw-joelmut**
Fixes #5713

## Description
This PR fixes an issue when BotFramework-CLI is not installed in the Operative System (OS), the tests hang while installing the library. Instead, when it isn't installed, the tests will fail, warning the user to install the library.

## Specific Changes
- Added validation to throw the error when the `mergeCommand` fails.
- Removed condition to install or update the `@microsoft/botframework-cli` library.
- Reordered the code to accommodate the changes, the logic remains the same, without the installation of the library.

## Testing
The following images show when there is no `bf-cli` install, and when there is.
image

### CODE REVIEW

**Comment by mrivera-ms** [comment]
@sw-joelmut, could you please make the change requested? Thank you.

**Comment by sw-joelmut** [comment]
> @sw-joelmut, could you please make the change requested? Thank you.

Hi @mrivera-ms, just to be sure we are on the right track to solve this issue.
The issue contains these suggested fixes:
> 1. A test be added that runs before the Dialogs.Declarative.Tests that fails if the prerequisite BF CLI is not installed.

- Instead of creating a new test, we added the prerequisite to the current ones.

> 2. Set a timeout for Dialogs.Declarative.Tests at 60 seconds. (This normally completes after 20 seconds.)

- We didn't increase the timeout, since the tests will finish earlier when BF CLI is not installed, installed or updated by the process.

Would you like us to apply the timeout to the tests as well?. Thank you.

**Comment by mrivera-ms** [comment]
@sw-joelmut, you don't need to add a method to perform the check because it introduces duplication. The error returned when running the new method is the same we get from the mergeCommand in line 39. Instead, you can use the error returned in line 39 and replace the attempt to install bf_cli with throwing the exception with this error message. Please see my notes inline.

**Comment by sw-joelmut** [comment]
> @sw-joelmut, you don't need to add a method to perform the check because it introduces duplication. If BF_CLI is not installed, the error returned when running the new method is the same we get from the mergeCommand in line 39. Instead, you can use the error returned in line 39 and replace the attempt to install bf_cli (line 61) with throwing the exception with this error message.

Thanks for the feedback @mrivera-ms.
We updated the code reusing the `mergeCommand`, more information can be found in the updated PR description.

**Review by gabog — APPROVED** [review]

**Pull request merged**
