### PR TITLE
Allow TelemetryInitializer properties to be overridden by user

### PR DESCRIPTION
**Pull request by daveta**
Fix issue that VA encountered.
Allow users to override telemetry that's logged from the initializer.

### CODE REVIEW

**Comment by cleemullins** [comment]
@daveta Does this need to be updated on the JS side as well?

**Comment by daveta** [comment]
Small update here: 
- I've got an outstanding query with Ben about functionality of nodejs.
- I believe nodejs at the moment has a bug where it's not placing the bot properties (so no chance of collision!)
- Based on implementation in nodejs, no chance of user overrides throwing an exception (like C#).
- HOWEVER, depending on the nodejs Application Insights hook we are using, it may not be possible to override the bot properties.  It all boils down to the order in which the hook gets called.  So, until (a) the bug gets fixed and (b) we can understand the order of invocation in nodejs, let's sit on this for a bit.  If a user cannot override, then for parity, we shouldn't "fix" this bug..

**Comment by cleemullins** [comment]
@daveta Any update on this?

**Comment by daveta** [comment]
Ok, so it appears the hook that we initialize the bot properties (now fixed) should be be overridable given restify calls it first.

It should behave the same way on both C# and node.

**Comment by cleemullins** [comment]
Per @daveta, "Yes, in js it's already there - you can consider this a js equivalence". 

Merging.

**Pull request merged**
