### PR TITLE
add StatusCode & ReasonPhrase to HttpResponseMock

### LINKED ISSUE #4360: Microsoft.Test.HttpRequestSequenceMock should be able to model errors
The HttpRequest mocking in the declarative testing only supports the content of a response and not the error code.  Without the error code, you cannot mock error situations.

Please add statusCode to the mock object and return it as part of the response.

[enhancement]

### PR DESCRIPTION
**Pull request by xieofxie**
Fixes #4360

## Description

add StatusCode & ReasonPhrase to HttpResponseMock

## Specific Changes

  - Mock HttpResponseMessage instead of Content

## Testing

Update TestScriptTests_HttpRequestMock.test.dialog

### CODE REVIEW

**Comment by xieofxie** [comment]
@chrimc62 I just copied all status codes.. Please review this, thanks~

**Comment by mrivera-ms** [comment]
Hello @xieofxie , please resolve the conflicts so we can merge this PR. Thanks.

**Comment by xieofxie** [comment]
Hi @mrivera-ms I resolve the conflict.

But I found something weird: my SchemaMergeTests would change the tests.schema very much and I don't think it should be so.

I am using @microsoft/botframework-cli@4.10.0-dev.20200730.3786d10 with @microsoft/bf-dialog v4.10.0-dev.20200730.3786d10 and I think they are the latest one.

Do I miss something?

**Comment by chrimc62** [comment]
> Hi @mrivera-ms I resolve the conflict.
> 
> But I found something weird: my SchemaMergeTests would change the tests.schema very much and I don't think it should be so.
> 
> I am using @microsoft/botframework-cli@4.10.0-dev.20200730.3786d10 with @microsoft/bf-dialog v4.10.0-dev.20200730.3786d10 and I think they are the latest one.
> 
> Do I miss something?

This is most likely because you do not have the rc version of bf cli installed.

**Pull request merged**
