### PR TITLE
[#6741] Update projects to .Net 8

### PR DESCRIPTION
**Pull request by ceciliaavila**
Addresses #6741
#minor

## Description
This PR updates the test projects, the test bots, and the CI pipelines to target .NET 8.
All these changes need to be done in one PR for the build checks to pass. 
We divided the changes into three commits to ease the review:

- Updated test projects ([7c65b52b127903bd74e0871c781d3dc551230646](https://github.com/microsoft/botbuilder-dotnet/commit/7c65b52b127903bd74e0871c781d3dc551230646))
- Updated test bots ([405c6fdccaa455007f68ce29fa82321257a9e0dd](https://github.com/microsoft/botbuilder-dotnet/commit/405c6fdccaa455007f68ce29fa82321257a9e0dd))
- Updated CI yamls ([ebbbf5d0433e58343d26acdeef3f2ca3c7cf5b8d](https://github.com/microsoft/botbuilder-dotnet/commit/ebbbf5d0433e58343d26acdeef3f2ca3c7cf5b8d))

_Note: The FunctionalTests pipelines and the generators will be updated in separate PRs._

## Specific Changes
- **For the test projects:**
   - Update projects to target net8.0 as well as net6.0.
   - Removed any conditions considering frameworks lower than .NET5.
   - Fixed [CS8981](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/warning-waves#cs8981---the-type-name-only-contains-lower-cased-ascii-characters) issue in Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ConditionalsTests

- **For the bots projects:**
   - Updated all the bots to target .NET8 instead of .NET6.

- **For the CI pipelines yamls:**
   - Added steps to build and test targeting .NET8.
   - Removed steps to build and test targeting netcoreapp3.1.

## Testing
This image shows the TestBot bots working as expected after the update.
image

Here we can see the CI pipeline working after the changes.
image

### CODE REVIEW

**Comment by BruceHaley** [comment]
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.Integration.AspNet.Core.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.TemplateManager.dll**

**Comment by tracyboehrer** [comment]
@ceciliaavila If it doesn't cause any issues, lets retain the 3.1 support in the packages.

**Comment by ceciliaavila** [comment]
> @ceciliaavila If it doesn't cause any issues, lets retain the 3.1 support in the packages.

Sure, we'll update the projects to keep supporting netcoreapp 3.1.

**Comment by tracyboehrer** [comment]
@ceciliaavila @sw-joelmut Were the changes to retain 3.1 support (if possible) made?

**Comment by tracyboehrer** [comment]
[like]  Tracy Boehrer reacted to your message:
________________________________

**Comment by BruceHaley** [comment]
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.Integration.AspNet.Core.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.TemplateManager.dll**

**Comment by JhontSouth** [comment]
Hi @tracyboehrer, the changes to maintain support for Net Core 3.1 are ready in the PR.

**Review by tracyboehrer — APPROVED** [review]

**Pull request merged**
