### PR TITLE
Split AI functionality into separate projects.

### PR DESCRIPTION
**Pull request by garypretty**
In order to improve consistency and in answer discussion in #324, I have done the following;

 * Split out QnA and Translation into their own Projects, to match the pattern used with LUIS, within a Microsoft.Bot.Builder.AI namespace (also moved LUIS into this namespace)
* Introduced an AI solution folder to allow for more projects to be added in the future
* Updated samples and unit test project references (all unit tests pass and samples build)

### CODE REVIEW

**Comment by garypretty** [comment]
@tomlm @cleemullins This is the new PR I said I would raise once Chris' PR got merged. Please review and let me know if you need any changes. Cheers!

**Comment by garypretty** [comment]
@tomlm @cleemullins I have merged in master into this branch to ensure we also have the latest changes around service caching etc. Cheers!

**Comment by cleemullins** [comment]
@garypretty Hey Gary, I'm ready to take this PR now, if you have a chance to fix the merge conflicts (again).  Sorry for the delay!

**Comment by garypretty** [comment]
@cleemullins Closing this. Opened #385 which is based on the latest branch, building and tests pass.

**Pull request closed without merging**
