### PR TITLE
Revert "Update OAuthPrompt.cs"

### PR DESCRIPTION
**Pull request by mingweiw**
Reverts microsoft/botbuilder-dotnet#1579

### CODE REVIEW

**Comment by fuselabs** [comment]
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Builder.dll
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Builder.AI.Luis.dll
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Builder.AI.QnA.dll
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Builder.ApplicationInsights.dll
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Builder.Azure.dll
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Builder.Dialogs.dll
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Builder.TemplateManager.dll
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Configuration.dll
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Connector.dll
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Schema.dll

**Comment by cleemullins** [comment]
@mingweiw Can you add more detail here around "Why revert?" Why do we need to revert? Should we do anything else in place of the code we're reverting? 

The original changes were made and verified with @jeffders, and if they're wrong we should figure out what to do.

**Comment by cleemullins** [comment]
Also, if we're reverting this here - what about the JS (any Python) codebase?

**Comment by benbrown** [comment]
We need to create a new issue to track this change in both languages, etc.

**Comment by cleemullins** [comment]
In REviewing all of Jeff's recent email w/ teams, the code that's there appears to be correct. I don't think this PR is needed.

**Pull request closed without merging**
