### PR TITLE
[StyleCop] Treat Warnings as Errors

### PR DESCRIPTION
**Pull request by ceciliaavila**
Solves ISSUE #1423

**Description**

Update the ruleset file to treat StyleCop warnings as errors

image

**NOTE:** To merge this PR is necessary that the PR #1473 is merged and that all the stylecop issues are solved.

### CODE REVIEW

**Comment by GasparAcevedoZainSouthworks** [comment]
This PR is ready for Review. However, it's important to notice that the Azure Build process will fail, as this PR attempts to treat the StyleCop Warnings as errors, and there are some remaining warnings to solve.

Note: the next PR fix the remaining Stylecop Warnings:
- #1618 
- #1620
- #1623 
- #1624 
- #1642

**Comment by cleemullins** [comment]
We're getting close to taking this. Are we ready? :)

**Comment by GasparAcevedoZainSouthworks** [comment]
> We're getting close to taking this. Are we ready? :)

Hi @cleemullins, we created one last PR for fixing the remaining Stylecop Warnings, this is the PR #1668. Once PR #1668 is merged, we will be ready for merging this one.

Also, we created PR #1667, which revert the fixes made on the TestBot.WebApi project (with PR #1642) and ignore all the Warnings there. This is not necessary to merge for treating Warnings as Errors.

**Comment by GasparAcevedoZainSouthworks** [comment]
Hi @cleemullins,

We performed a last build of the whole Solution just for checking if there are some remaining Stylecop Warnings, but there isn't any of them. So, we can Merge this PR.

**Comment by fuselabs** [comment]
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Builder.dll
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Builder.AI.Luis.dll
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Builder.AI.QnA.dll
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Builder.ApplicationInsights.dll
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Builder.Azure.dll
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Builder.Dialogs.dll
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Builder.TemplateManager.dll
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Configuration.dll
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Connector.dll
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Schema.dll

**Comment by cleemullins** [comment]
@ceciliaavila Are we ready to take this? Could you "touch" the PR so it triggers a new build? If the build passes, let's merge it in.

**Comment by ceciliaavila** [comment]
> @ceciliaavila Are we ready to take this? Could you "touch" the PR so it triggers a new build? If the build passes, let's merge it in.

Hi Chris, we just rebased this PR and found that there are new errors. We will be fixing them. Once they are solved, we will let you know.

**Comment by ceciliaavila** [comment]
> > @ceciliaavila Are we ready to take this? Could you "touch" the PR so it triggers a new build? If the build passes, let's merge it in.
> 
> Hi @cleemullins, we just rebased this PR and found that there are new errors. We will be fixing them. Once they are solved, we will let you know.

Hi @cleemullins, we created the PR #2068 with the fix of the new StyleCop issues founded. After it gets merged, we can rebase this PR to merge it too. 
Thanks!

**Comment by fuselabs** [comment]
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.AI.Luis.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.AI.Luis/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.AI.QnA.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.AI.QnA/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.ApplicationInsights.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.ApplicationInsights/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.Azure.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.Azure/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.Dialogs.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.Dialogs/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.TemplateManager.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.TemplateManager/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Configuration.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Configuration/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Connector.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Connector/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Schema.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Schema/4.3.1)

**Comment by gabog** [comment]
Hi @ceciliaavila, it looks like the branch got outdated, can you resolve the conflicts and ping me when is done and I will review again.

Thanks

**Comment by fuselabs** [comment]
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.AI.Luis.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.AI.Luis/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.AI.QnA.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.AI.QnA/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.ApplicationInsights.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.ApplicationInsights/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.Azure.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.Azure/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.Dialogs.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.Dialogs/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.TemplateManager.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.TemplateManager/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Configuration.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Configuration/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Connector.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Connector/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Schema.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Schema/4.3.1)

**Comment by fuselabs** [comment]
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.AI.Luis.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.AI.Luis/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.AI.QnA.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.AI.QnA/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.ApplicationInsights.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.ApplicationInsights/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.Azure.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.Azure/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.Dialogs.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.Dialogs/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.TemplateManager.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.TemplateManager/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Configuration.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Configuration/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Connector.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Connector/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Schema.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Schema/4.3.1)

**Pull request merged**
