### PR TITLE
Add ContinueConversationAsync to IAdapterIntegration

### LINKED ISSUE #1287: IAdapterIntegration interface needs to expose ContinueConversationAsync to enable proactive scenarios
**Is your feature request related to a problem? Please describe.**
Unable to execute proactive callback scenarios in an abstract way because the `IAdapterIntegration` abstraction does not expose the method to trigger.

**Describe the solution you'd like**
`IAdapterIntegration` should expose `ContinueConversationAsync` so that I can trigger proactive callbacks via this abstraction.

**Describe alternatives you've considered**
Downcasting the `IAdapterIntegration` to `BotAdapter` works, but it makes a hard assumption on an the implementation detail and also makes unit testing more difficult.

**Additional context**
[This also came up recently in a discussion on another issue.](https://github.com/Microsoft/botbuilder-dotnet/issues/787#issuecomment-453551626). There is more to the discussion which I of course suggest reading, but this particular shortcoming starts at that link.

**Sample code**
Here's a sample of a proprietary backend controller that I might have that handles events from some other system and finds a related conversation reference that it will proactively continue the conversation for:

```CSharp
    [Route("some-backend")]
    public class ProactiveController
    {
        private readonly IAdapterIntegration _adapterIntegration;

        public ProactiveController(IAdapterIntegration adapterIntegration)
        {
            _adapterIntegration = adapterIntegration ?? throw new ArgumentNullException(nameof(adapterIntegration));
        }

        [Route("events")]
        [HttpPost]
        public async Task<IActionResult> TriggerEvent([FromBody]SomeCustomEvent event, CancellationToken cancellationToken)
        {
            var botAppId = GetBotAppIdFromConfig();
            var conversationReference = await GetConversationReferenceRelatedToEventAsync(event);
           
            // Here's the downcast that breaks the abstraction just to call ContinueConversationAsync
            await ((BotAdapter)_adapterIntegration)
                .ContinueConversationAsync(
                botAppId,
                conversationReference,
                (turnContext, cancellationToken) =>
                {
                    // … whatever logic ...
                },
                cancellationToken);

            return new NoContentResult();
        }
    }
```

[enhancement]

### PR DESCRIPTION
**Pull request by drub0y**
Fixes #1287

### CODE REVIEW

**Comment by drub0y** [comment]
This effectively just copies the signature from the `BotAdapter` to the `IAdapterIntegration` abstraction.

**Comment by cleemullins** [comment]
@drub0y , The build error says this: 

tests\Microsoft.Bot.Builder.TestBot\InteceptorAdapter.cs(11,38): Error CS0535: 'InteceptorAdapter' does not implement interface member 'IAdapterIntegration.ContinueConversationAsync(string, ConversationReference, BotCallbackHandler, CancellationToken)'
tests\Microsoft.Bot.Builder.TestBot.WebApi\InteceptorAdapter.cs(11,38): Error CS0535: 'InteceptorAdapter' does not implement interface member 'IAdapterIntegration.ContinueConversationAsync(string, ConversationReference, BotCallbackHandler, CancellationToken)'
Process 'msbuild.exe' exited with code '1'.

(Note: Amusingly, InteceptorAdapter looks to be spelled wrong. If you're in there anyway, could you fix the spelling error?)

**Comment by cleemullins** [comment]
I wonder - does adding a method to an interface definition count as a breaking change? It clearly is (as seen by the broken build), but I'm not sure what to make of that. 

This *seems* like a class that's deep enough that nobody would be broken by taking the change.

**Comment by drub0y** [comment]
So it's really strange that I didn't hit this locally, I will run that to grounds and get whatever fix is necessary in.

**Comment by drub0y** [comment]
So, I really don't know what I did that missed this because I usually just build the whole solution, but clearly I must have built some subset. The problem was sample `IAdapterIntegration` classes in the `Test` apps in the solution, called `IntercepterAdapter`, that needed to implement the new method of the interface. Should be fixed, waiting on server build.

**Comment by drub0y** [comment]
> I wonder - does adding a method to an interface definition count as a breaking change? It clearly is (as seen by the broken build), but I'm not sure what to make of that.

Just to keep the discussion up to date here, @cleemullins had an offline chat and, yes, this is a breaking change because people who may have implemented the interface would be broken and need to implement the new method. In your own app this might not be a big deal, but if you took a dependency on another package that implemented a class with this interface it would be a bigger issue. You would have to wait until that package provided a compatible version before you could upgrade the BBSDK.

The decision will need to be made if this is the exact approach taken to keep things simple because there probably aren't many people out there who have implemented this interface or if we need to consider a different change (e.g. the old `IAdapterIntegration2` approach). I can't imagine anyone out there has implemented this interface themselves yet and then it should just be called out as a minor breaking change in the release notes for the rare case that someone did. My only other thought is: strict adherence to semver rules can cripple progress, so it really needs to be weighed and decided upon on a case by case basis. 

Finally, this is the reason why the C# team is working on [the default interface implementations feature](https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md).

**Pull request merged**
