### PR TITLE
DCR : Support for Channel Extensions as a first level concept

### PR DESCRIPTION
**Pull request by RamjotSingh**

### CODE REVIEW

**Comment by cleemullins** [comment]
@RamjotSingh Can you please describe the conceptual scenario, and the solution, in Markdown? In looking at this code both myself and @johnataylor didn't understand what the overall goals/motivation is. If you could lay out the problem more clearly, that would be a huge help.

**Comment by RamjotSingh** [comment]
@cleemullins I opened this PR to try to solve the issue of a streamlined way of creating Channel extensions. Sid has kept a meeting to discuss this more. But in very few words this PR is trying to outline 2 interfaces which can be implemented by channels like MsTeams, Skype etc. and then these packages can be seamlessly integrated with the BotFrameworkAdapter and will be available when processing activity from a specific channel.

This PR is aiming to upgrade extensions to being a first level concept and allow easy discoverability and usage.

**Comment by drub0y** [comment]
I feel like this can be built as an add-on around the core APIs that already exist; no need to augment `BotFrameworkAdapter` or `ITurnContext` directly. 

All you need is a piece of middleware which can sniff the channel, use the provider model you've got here to create an instance of the correct extension from the channel provider and then store it into the turn state. Then add some extension methods around `ITurnContext` that allow you to retrieve the channel extension for use in downstream middleware and the bot.

**Comment by cleemullins** [comment]
@RamjotSingh I'm not clear on what the plans are for this branch. Before merging, it would need to be rebased. For now, I'm closing it out as it appears it's not going to be part of the 4.2 release.

**Pull request closed without merging**
