### PR TITLE
[StyleCop] Fix all the warnings on several libraries

### PR DESCRIPTION
**Pull request by GasparAcevedoZainSouthworks**
**Libraries**: 

•	Bot.Builder.AppInsights.Tests
•	Bot.Builder.Integration.AppInsights.Core
•	Bot.Builder.Dialogs.Tests
•	Bot.Builder.AI.LUIS
•	Bot.Builder
•	Bot.ApplicationInsights.core.Tests

**Changes made**:

•	Remove trailing whitespace
•	Remove multiple blank lines in a row
•	Add documentation for type parameter <T>

### CODE REVIEW

**Comment by cleemullins** [comment]
```
No issues found in Microsoft.Bot.Builder.dll
No issues found in Microsoft.Bot.Builder.AI.Luis.dll
No issues found in Microsoft.Bot.Builder.AI.QnA.dll
No issues found in Microsoft.Bot.Builder.ApplicationInsights.dll
No issues found in Microsoft.Bot.Builder.Azure.dll
No issues found in Microsoft.Bot.Builder.Dialogs.dll
No issues found in Microsoft.Bot.Builder.TemplateManager.dll
No issues found in Microsoft.Bot.Configuration.dll
No issues found in Microsoft.Bot.Connector.dll
No issues found in Microsoft.Bot.Schema.dll

```

**Comment by munozemilio** [comment]
Hi @GasparAcevedoZainSouthworks, PR is approved but has conflicts, could you please fix those?

Thanks!

**Comment by cleemullins** [comment]
```
No issues found in Microsoft.Bot.Builder.dll
No issues found in Microsoft.Bot.Builder.AI.Luis.dll
No issues found in Microsoft.Bot.Builder.AI.QnA.dll
No issues found in Microsoft.Bot.Builder.ApplicationInsights.dll
No issues found in Microsoft.Bot.Builder.Azure.dll
No issues found in Microsoft.Bot.Builder.Dialogs.dll
No issues found in Microsoft.Bot.Builder.TemplateManager.dll
No issues found in Microsoft.Bot.Configuration.dll
No issues found in Microsoft.Bot.Connector.dll
No issues found in Microsoft.Bot.Schema.dll

```

**Comment by GasparAcevedoZainSouthworks** [comment]
> Hi @GasparAcevedoZainSouthworks, PR is approved but has conflicts, could you please fix those?
> 
> Thanks!

Hi @munozemilio, conflicts solved!!!

**Pull request merged**
