### PR TITLE
Update Microsoft.Bot.Builder.AI.Orchestrator.csproj

### PR DESCRIPTION
**Pull request by tsuwandy**
Fixes #
#5037 

## Description
Updated reference to Microsoft.BotFramework.Orchestrator to latest with fixes for MacOS 10.14/10.15.

### CODE REVIEW

**Review by taicchoumsft — APPROVED** [review]

**Comment by tsuwandy** [comment]
@mrivera-ms , not sure why those validation fails.  Could you help?  Thanks!

**Comment by mrivera-ms** [comment]
> @mrivera-ms Monica Rivera FTE , not sure why those validation fails. Could you help? Thanks!

Hi Tien, the errors are due to an incompatibility between the Nuget version in use on that branch and the latest update to msbuild. Did you intend to check this into the 4.11 branch?

**Pull request merged**
