### PR TITLE
Remove proactive endpoint from integrations

### PR DESCRIPTION
**Pull request by drub0y**
[It has been decided in #461 that we will not offer a proactive (aka event)
backchannel endpoint in the box at this time](https://github.com/Microsoft/botbuilder-dotnet/pull/461#issuecomment-408187032), so this removes the
current implementation that was there.

### CODE REVIEW

**Comment by drub0y** [comment]
For historic purposes in case people stumble across this and wonder what they're supposed to do now: the proposed work around for this that is that developers just add their own controller and take the `IBot` (or `BotAdapter`) via DI into that controller.

IMHO that's boiler plate that a lot of devs will end up writing, so having another package that offers this functionality would still be nice and I may try to factor this out as it would be a good exercise around the extensibility story of the SDK as well.

**Comment by cleemullins** [comment]
Thanks Drew. 

I agree with every point you made in the PR. For the immediate term, this makes the docs teams (and samples) easier, as it's just less surface area.

**Comment by odannyc** [comment]
@drub0y 

The workaround is no longer possible with the newest botbuilder version (4.2.0)
I keep getting these errors:

```InvalidOperationException: Unable to resolve service for type 'Microsoft.Bot.Builder.BotAdapter'```

If I try to inject `BotFrameworkAdapter` I get:

```InvalidOperationException: Unable to resolve service for type 'Microsoft.Bot.Builder.BotFrameworkAdapter'```


It seems like those are no longer being registered in DI in botbuilder

**Comment by drub0y** [comment]
Yep... except `IAdapterIntegration` does not expose the full API of `BotAdapter`, specifically needed for proactive would be `ContinueConversation` so, for now, you must blindly cast the `IAdapterIntegration` to `BotAdapter`. I have this on a list of things to discuss with the team.

**Pull request merged**
