### PR TITLE
 [LG] Move "EXPRESSION" in LG from lexer to parser

### PR DESCRIPTION
**Pull request by Danieladu**
close: #3840
Move "EXPRESSION" in LG from token to parser to get more detailed contextual information.
Which would benefit some external tools like Expression debugging tool.

Orignially, customers can not anchor the expression correctly, they can only get the context of the whole content which contains this expression. For example, for multiline context, 
```
# template
 - ```
 ${expression1}
 ${expression2}```
```

in this situation, the code range of "expression1" we can get is [1 ~ 3]， which is the whole content of multi-line, But after migrating experssion from token to parser, we can locate the "expression1" correctly, which starts from line 2, char 1, to line 2, char 14. That would be very helpful for some debugging tools.

For example, in [adaptive-tool](https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/adaptive-tool) debugging tool, if someone wants to set a breaking point for a expression in multiline, it is not possible, because you should set the whole multiline as the breaking point. The change of this pr make is possible. 
In another case, if someone wants to set a breaking point for different expressions which in the same line, originally, it is impossible.
`- ${expr1}  ${expr2}`,
Because the minimum granularity of the context is the normal template line. But, now , it is possible. You can set a single breaking point for only "expr2" or just for "expr1"

### CODE REVIEW

**Comment by boydc2014** [comment]
One suggestion is you can update your title to represent the impact of the work rather than the actually task, perhaps will carry your message more accurate.

**Comment by chrimc62** [comment]
Can we get some tests around this?

**Comment by Danieladu** [comment]
> Can we get some tests around this?

This change would not change any evaluation result, and just make the expression type from "lexer" to "parser".

**Comment by boydc2014** [comment]
> > Can we get some tests around this?
> 
> This change would not change any evaluation result, and just make the expression type from "lexer" to "parser".

i think we still need some tests, don't have to be in evaluation tests, we can just create certain tests on the parseTree, right?

**Comment by Danieladu** [comment]
> i think we still need some tests, don't have to be in evaluation tests, we can just create certain tests on the parseTree, right?

I have added some parseTree tests.

**Pull request merged**
