### PR TITLE
Added test case to test the Exception aggregation

### PR DESCRIPTION
**Pull request by RyanDawkins**
Added test case to test the Exception aggregation

### CODE REVIEW

**Comment by drub0y** [comment]
Those changes just went in and added one more test to the suite to cover the scenario where the exception happens in `OnReceive`. It also changes the exception handling so that the underlying exception propagates more "naturally" through the task chain as a `AggregateException`. Glancing at the test you added here it should work exactly the same way since you're checking the inner exception's type. So if you rebate against my commit and rerun it should "just work". 😊

**Comment by cleemullins** [comment]
Are you on skype? Or teams? Or slack?

________________________________

**Comment by cleemullins** [comment]
Merged.

________________________________

**Comment by RyanDawkins** [comment]
I'm about to pull in the changes if you pulled stuff into your branch.

**Comment by RyanDawkins** [comment]
@cleemullins I can close this PR and open another for master? I noticed you already merged your branch in.

**Pull request closed without merging**
