### PR TITLE
fix waterfall and steps

### PR DESCRIPTION
**Pull request by codefoster**
I did not appear the waterfall steps were doing what was intended. Looked like a copy/paste error.
I also simplified the syntax a bit too which IMO makes the sample easier to grok.

### CODE REVIEW

**Comment by codefoster** [comment]
I added lines to some of the steps in this PR to display if the user types anything between steps, but just realized that that may conflict conceptually with the WaterfallAndPromptBot sample, so consider removing those.

**Comment by cleemullins** [comment]
@johnataylor - John, can you take a look?

**Comment by codefoster** [comment]
@johnataylor, okay, it's very possible that I didn't understand the original sample and the concept that it was relaying. Perhaps I should just raise the feedback that I'm not sure what this sample is attempting to illustrate and some documentation is necessary. On line 105 the bot is saying "step**1**.1" from within Waterfall**2**_Step1. Likewise, on line 114 it's saying "step**2**.1" from within Waterfall**3**_Step1. Are those typos or intended?

**Comment by johnataylor** [comment]
Perhaps a could clean up the naming. Basically this comes from me porting (verbatim) Steve's Dialog/Waterfall/Prompt model to C#. We may well iterate on this model, however, having model be the same on each platform seems like a sane place to be.

So as I played around with this a little I thought it was meaningful to see how various permutations of composition worked out. Here I was attempting to kick of nested Waterfalls from a parent. So the parent is two steps but each step has in turn a child two step Waterfall. Anyhow you can experiment with the behavior in the emulator. The behavior should be exactly the same as the JavaScript implementation if it isn't that's a bug.

**Comment by johnataylor** [comment]
We will review the samples all up now we have ChoicePrompt coming in.

**Pull request closed without merging**
