### PR TITLE
Allowing Middlewares access to AppId and thus allow them to get their own tokens

### PR DESCRIPTION
**Pull request by RamjotSingh**
Exposing AppId thru the layers (using IBotContext). This way Middlewares can use ICredentialProvider and AppId to get their own tokens. This allows developers to build extensions which utilize their owns tokens (e.g. Graph etc.) to enable enchanced scenarios.

### CODE REVIEW

**Comment by RamjotSingh** [comment]
@cleemullins I have closed the other PR and merged all the changes here (GitHub went crazy and stopped updating my PR for some reason).

**Comment by RamjotSingh** [comment]
@cleemullins Can you take a look at this?

**Comment by RamjotSingh** [comment]
This is the only scalable solution that came to my mind without special casing AppId and ServiceUrl. If you have some other better solution in mind I would be happy be make changes.

**Comment by cleemullins** [comment]
Ramjsing & I spoke, and we're going to meet in person on Friday and see if we can find a way to accomplish the same results without having to change the signatures and flow of quite so much code.

**Comment by tomlm** [comment]
With the new Adapter merge I don't think we need to do this any more.

**Pull request closed without merging**
