### PR TITLE
Fix telemetry for custom adapters

### PR DESCRIPTION
**Pull request by garypretty**
Fixes: #2477 
Fixes: #2474 

This change introduces TelemetryInitializerMiddleware, as a replacement for the current TelemetrySaveBodyASPMiddleware.  Marking this PR as review for now until a few people have their chance to review, given a few conversations last week with @munozemilio @daveta among others. 

This existing method stores the incoming http request body in the HttpContext.Items collection.  This is later used by the TelemetryBotIdInitializer classes within the integration libraries to parse the request and set conversation / user / activity channel IDs on outgoing Application Insights requests. The current problem is that the current method assumes an incoming request is a Bot Framework Activity, but if a custom adapter is used, the incoming http request may be something different. This change moves the responsibility for storing the activity in HttpContext.Items into the new middleware class.  This ensures that it can be used by custom adapters and will store an activity once it has been transformed by the adapter.

This is a non-breaking change, given that the existing method using the TelemetrySaveBodyASPMiddleware can be used alongside the new middleware.  However, I have marked the existing methods as obselete as a prompt to users to start to use the new TelemetryInitialzerMiddleware.

I have tested the following scenarios, where all existing telemetry (including RequestTelemetry and EventTelemetry) is captured correctly.

- Bot Framework adapter using the new middleware
- Bot Framework adapter using the new middleware & old method along side
- Custom adapter (Alexa community adapter) using the new middleware
- Custom adapter (Alexa community adapter) using the new middleware & old method along side

TODO:

- Update the Core Bot App Insights sample
- Update the telemetry docs if required
- Identify if this custom adapter issue exists within the other languages and raise parity issues if required

### CODE REVIEW

**Comment by fuselabs** [comment]
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.AI.Luis.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.AI.Luis/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.AI.QnA.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.AI.QnA/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.ApplicationInsights.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.ApplicationInsights/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.Azure.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.Azure/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.Dialogs.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.Dialogs/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.TemplateManager.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.TemplateManager/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Configuration.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Configuration/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Connector.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Connector/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Schema.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Schema/4.3.1)

**Comment by daveta** [comment]
Awesome - nice work!
Gary, do you have some kind of test or sample for initialization adding the new Initializer Middleware?  I'm just wondering if a specific order needs to be adhered to.  Also, if Request works in replacing userid/session, i'm assuming Dependency also works (?).  
I really like the new overridable OnTurn method!

**Comment by garypretty** [comment]
@daveta No, DependencyTelemetry requests are not amended at present, but that is bacause, as per this line https://github.com/microsoft/botbuilder-dotnet/blob/b84a82f784b3276c66ea831f02035b8f9ec324e2/libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/TelemetryBotIdInitializer.cs#L38 we only currently append properties on specific types of app insights request.
That feels like a bug to me - we should probably add DependencyTelemetry to that check as well. You agree?

In terms of order, I would suggest that this is placed as early in the middleware pipeline as possible (ideally always the first item), to ensure any other pieces of middleware that make use of TelemetryClient have their app insight requests correctly updated.  Therefore, this does need to sit ahead of TelemetryLoggerMiddleware (if it is used).

**Comment by garypretty** [comment]
@daveta We do have a couple of options that could make the ordering problem, specifically with TelemetryLoggerMiddleware easier. 

- Have TelemetryLoggerMiddleware store the activity on the HttpContext (if it isn't already there) - this means that a user only has to use TelemetryLoggerMiddleware.

- We then have the additional option of simply keeping this new functionality in the TelemetryLoggerMiddleware class. Right now we have this piece of middleware as optional if you want to log activity events, but we could add an optional parameter which allows a user to enable / disable activity logging, which would make this the only piece of telemetry middleware needed, instead of adding another.  I personally like this option - keeps things simple.

**Comment by fuselabs** [comment]
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.AI.Luis.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.AI.Luis/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.AI.QnA.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.AI.QnA/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.ApplicationInsights.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.ApplicationInsights/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.Azure.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.Azure/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.Dialogs.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.Dialogs/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.TemplateManager.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.TemplateManager/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Configuration.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Configuration/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Connector.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Connector/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Schema.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Schema/4.3.1)

**Comment by daveta** [comment]
@garypretty : Yeah, I think alot of interesting things come from Dependency.  And consolidating into a single Middleware would be awesome!

**Comment by fuselabs** [comment]
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.AI.Luis.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.AI.Luis/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.AI.QnA.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.AI.QnA/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.ApplicationInsights.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.ApplicationInsights/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.Azure.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.Azure/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.Dialogs.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.Dialogs/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.TemplateManager.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.TemplateManager/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Configuration.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Configuration/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Connector.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Connector/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Schema.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Schema/4.3.1)

**Comment by garypretty** [comment]
@daveta I have added the change in to include DependencyTelemetry.  I have held off combining with the TelemetryLoggerMiddleware, as this would be a breaking change, given that middleware is currently within Microsoft.Bot.Builder core.  I think we can keep this non-breaking and simply have the new middleware and ensure the docs and samples are updated.

**Comment by garypretty** [comment]
@daveta @munozemilio I have removed the [Do not merge] flag from this as I think it is ready to go. @lauren-mills has confirmed that this approach fixes the issues that is currently blocking customers getting telemetry for skills using the web socket adapter.

@cleemullins I am not clear at the moment if this issue affects the other languages, given that the issue causing the problem appears to be specific to the .Net implementation.  I will raise an issue in each where telemetry has been implemented for us to confirm.

**Comment by daveta** [comment]
@garypretty: Looks good, do any tests need to be updated?

Also, you may run by @johnataylor about the Middleware ordering requirement.  We had a previous middleware that had a similar ordering requirement, and it was confusing for people.

**Comment by garypretty** [comment]
Thanks @daveta.I'll check the tests.

@johnataylor would appreciate any comments as per @daveta's note. We thought about other options, but this is the only one that seemed to maintain compat and not overcomplicate the solution. I'm thinking here we can handle the ordering of middleware in our samples / docs, as setting up telemetry is basically a one and done task - also the naming TelemetryInitializerMiddleware hopefully also suggests it should come before something like TelemetryLoggerMiddleware.

Any questions let me know.

**Comment by garypretty** [comment]
@daveta I have resolved the potential issue with middleware out of order by having the TelemetryInitializerMiddleware call the TelemetryLoggerMiddleware (flag to enable / disable this within the constructor. Defaults to true). I also added unit tests for the middleware and also a test for the addition of DependencyTelemetry.

**Comment by fuselabs** [comment]
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.AI.Luis.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.AI.Luis/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.AI.QnA.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.AI.QnA/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.ApplicationInsights.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.ApplicationInsights/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.Azure.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.Azure/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.Dialogs.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.Dialogs/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.TemplateManager.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.TemplateManager/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Configuration.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Configuration/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Connector.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Connector/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Schema.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Schema/4.3.1)

**Pull request merged**
