### PR TITLE
[Debugger] add injectable transport, with unit tests

### PR DESCRIPTION
**Pull request by willportnoy**
## Description
This PR allows the debugger transport to be injectable to
1. simplify the debug adapter code
2. remove implementation inheritance
3. allow unit tests (with mocked transports) for the debug adapter code

## Specific Changes
  - create new IDebugTransport interface
  - move code to use IDebugTransport interface
  - add first substantial unit test for debug adapter

## Testing
Yep.

### CODE REVIEW

**Comment by mrivera-ms** [comment]
@gabog, could you please review?

**Comment by mrivera-ms** [comment]
@gabog will review.

**Comment by gabog** [comment]
@mrivera-ms & @willportnoy, looking at this today, it may take a bit. Sorry for the delay.

**Review by gabog — APPROVED** [review]
Tested this with TestJson and it works well, need to work on making it work with TestScript but we can address this separately.

**Pull request merged**
