### PR TITLE
remove cloud adapter classes from webapi

### PR DESCRIPTION
**Pull request by johnataylor**
remove cloud adapter classes from webapi

### CODE REVIEW

**Review by EricDahlvang — APPROVED** [review]

**Review by carlosscastro — CHANGES_REQUESTED** [review]
@johnataylor could you confirm that we can delete these classes? If they did ship in R11, we need to be careful with backward compat. Let's confirm that this is not a breaking change and if not we can let this one through.

**Comment by johnataylor** [comment]
> @johnataylor could you confirm that we can delete these classes? If they did ship in R11, we need to be careful with backward compat. Let's confirm that this is not a breaking change and if not we can let this one through.

Yes this is new code this milestone so never released.

**Review by gabog — CHANGES_REQUESTED** [review]
@carlosscastro, @johnataylor, checked the [R11 branch](https://github.com/microsoft/botbuilder-dotnet/tree/4.11/libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi) and this classes were released back then.

I'm OK with deleting them but we need to create an issue to describe the change and put it into release notes.

**Review by carlosscastro — APPROVED** [review]
@johnataylor @EricDahlvang @cleemullins  and I jsut talked and agreed to remove. AS @gabog mentioned, would be good if @johnataylor adds a new work item for release notes. Approving now but please link to the work item so what we get good visibility.

**Review by mrivera-ms — APPROVED** [review]

**Review by gabog — APPROVED** [review]

**Pull request merged**
