### PR TITLE
Split AI project into individual projects (resolved conflicts)

### PR DESCRIPTION
**Pull request by garypretty**
@cleemullins This PR replaces #343 and exists to resolve various merge issues with that PR 

In order to improve consistency and in answer discussion in #324, I have done the following;
* Split out QnA and Translation into their own Projects, to match the pattern used with LUIS, within a Microsoft.Bot.Builder.AI namespace (also moved LUIS into this namespace)
* Introduced an AI solution folder to allow for more projects to be added in the future
* Updated samples and unit test project references (all unit tests pass and samples build)

### CODE REVIEW

**Comment by cleemullins** [comment]
@tomlm Tom - this looks good to me. Want to take a quick look before I merge it?

**Comment by cleemullins** [comment]
@garypretty Ah! I see conflicts again. :( I was just about to merge it.

**Comment by garypretty** [comment]
@cleemullins No worries. I will sort this later and ping you once done :)

**Comment by garypretty** [comment]
@cleemullins no worries. I'll sort that later and ping you when done.

**Comment by garypretty** [comment]
@cleemullins merged master in. conflicts resolved and it is building. Let's merge it quick :)

**Comment by cleemullins** [comment]
@garypretty It looks like there's still one merge conflict. I was about to check it in *again* !

**Comment by garypretty** [comment]
@cleemullins wait. I was asleep for like an hour! 😂 Will resolve later when I get back and let you know.

**Comment by garypretty** [comment]
@cleemullins conflict resolved :) 👍

**Comment by cleemullins** [comment]
@garypretty  It's in! It's in!!

**Pull request merged**
