### PR TITLE
add new GetAnswersAsync method with QnAMakerOptions param

### PR DESCRIPTION
**Pull request by adiazcan**
to fix this new feature #1083, I created a new method with QnAMakerOptions parameter

### CODE REVIEW

**Comment by adiazcan** [comment]
I updated the my code with @MeghaChaitanya suggestion

**Comment by vishwacsena** [comment]
@johnataylor @cleemullins - can you please review? Note this is has been reviewed and approved by @MeghaChaitanya from the QnA Maker team.

**Comment by vishwacsena** [comment]
We need a JS side of this fix as well tracked via Microsoft/botbuilder-js/issues/551

**Comment by johnataylor** [comment]
I'm closing this PR in favor of #1200 
@stevengum 
refer to notes in the other PR

**Pull request closed without merging**
