### PR TITLE
[#4888] [Slack Adapter] Make messages with attachments into message activities

### LINKED ISSUE #4888: Activity.Text is set to filename and not the message text when sending a Slack message with attachment
## Version
What package version of the SDK are you using. __4.10.3__

## Describe the bug
When sending a message in Slack with an attachment, the `turnContext.Activity.Text` property is populated with the file name and not the message text.

## To Reproduce
1. Create a bot and connect it to Slack using Azure Bot Service.
2. In Slack, type a message that also includes an attachment.
3. Check out the properties of `turnContext` in `OnMessageActivityAsync`

## Expected behavior
__Expected__ that `turnContext.Activity.Text` is populated with the Slack message ("hey there, here's an attachment" in the screenshot.)
__Actual:__ `turnContext.Activity.Text` is populated with the file name of the uploaded attachment.

## Screenshots
Screen Shot 2020-10-29 at 8 45 06 PM

## Additional context
I can see the message in `ChannelData`, but I think the current behavior is incorrect. `Text` should be the message. It's already possible to get the attachment filename via the `Attachments` property. For example, if I attach multiple files, the `Text` property is populated with just one of those file names.

### PR DESCRIPTION
**Pull request by denscollo**
Fixes #4888

## Description
Updates the Slack Adapter to resolve received messages with attachments as `ActivityTypes.Message`, allowing users to access the _text_ and _attachment_ properties from the root activity.

**THIS IS A BREAKING CHANGE 
Messages with attachments will be received "on message" activities instead of "on event" activities.**

The change makes attachment messages more akin to ABS, which also interprets them as message activities but lacks the text property, using the attachment name instead.

image

## Specific Changes

  - Adds received messages with attachments to the filter to resolve them as message activities.
    - Obtains each file's properties manually to parse them into `Attachments`

## Testing
The changes were tested in unit and functional tests with no issues, since there are no message with attachment tests affected.
image

### CODE REVIEW

**Review by carlosscastro — CHANGES_REQUESTED** [review]
Thanks @denscollo ! We have a number of Slack helper tests already. Could we add a new test that would fail without your fix and passes with your fix? If it is not possible please let us know, but seems possible at a quick glance.

**Comment by mrivera-ms** [comment]
@denscollo, could you please see the request above?

**Comment by denscollo** [comment]
@carlosscastro @mrivera-ms sure! We are currently working on it, as soon as we have it ready we'll let you know. Thanks!

**Comment by denscollo** [comment]
@carlosscastro @mrivera-ms We just pushed the changes with the new test.

**Review by carlosscastro — APPROVED** [review]

**Review by mrivera-ms — APPROVED** [review]

**Pull request merged**
