### PR TITLE
Drop ADAL to unblock pipeline

### PR DESCRIPTION
**Pull request by Danieladu**
Fixes #minor

## Description
ADAL library (Microsoft.IdentityModel.Clients.ActiveDirectory,Microsoft.Azure.Services.AppAuthentication ) has been marked deprecated and would block the Azure pipeline on 23 September.

Totally remove ADAL code to unblock the pipeline

### CODE REVIEW

**Review by sw-joelmut — APPROVED** [review]
Hi @Danieladu,

The changes are looking good! About the CI exception, this PR is introducing breaking changes.

@tracyboehrer, to merge this PR you'll need to exclude these classes from the compat check by adding them to the list in the  `ApiCompatExcludeClasses` variable.

For more information, check out the PR [#5124](https://github.com/microsoft/botbuilder-dotnet/pull/5124).

**Comment by Danieladu** [comment]
I have updated the variable, but seems not work
image
Is there any additional thing should i do?

**Comment by sw-joelmut** [comment]
Hi @Danieladu,

We want to share our findings regarding the `ApiCompatExcludeClasses` variable.
The variable is working as expected, but you will need to execute the pipeline (`new run, not retry`) for the changes to be applied.
imagen

Additionally, there is another way of excluding the classes.
All compatibility issues shown in the `Compatibility Check` pipeline's section can be excluded by adding them to the [ApiCompatBaseline.txt](https://github.com/microsoft/botbuilder-dotnet/blob/main/ApiCompatBaseline.txt) file.
imagen

**Comment by Danieladu** [comment]
@microsoft/botframework-sdk please help review this PR which blocks the SDK pipeline and also ABS pipeline.

**Review by tracyboehrer — APPROVED** [review]

**Pull request merged**
