### PR TITLE
Add DirectLineClientTests to FunctionalTest project using ARM

### PR DESCRIPTION
**Pull request by ceciliaavila**
## Proposed Changes

Add new **DirectLineClientTests** to _FunctionalTests_ project to test sending a message to an echo bot deployed in Azure with ARM Templates and check its response.
image
## Steps to configure the Pipeline:
1- Define three environment variables: **AppId**, **AppSecret** and **BotName** and mark the first two as Secrets.
image
image
2- Add a **_PowerShell Script Task_** to download the .zip that contains the latest version of the EchoBot Sample.

image

The script is:
```powershell
$url = "https://dev.botframework.com/api/misc/bottemplateroot"
$output = "$(System.DefaultWorkingDirectory)\FunctionalTests\echoBot.zip"

$partialUrl = Invoke-WebRequest -Uri $url

$cleanUrl = $partialUrl -replace'["]'

$completeUrl = "$($cleanUrl)csharp-abs-webapp-v4_echobot_precompiled.zip"

$wc = New-Object System.Net.WebClient
$wc.DownloadFile($completeUrl, $output)

Expand-Archive $output -DestinationPath $(System.DefaultWorkingDirectory)\FunctionalTests\echoBot\

$slnPath = Get-ChildItem -Path $(System.DefaultWorkingDirectory)\FunctionalTests\echoBot\ -Filter EchoBot.sln -Recurse -Force -ErrorAction SilentlyContinue| select FullName

$folder = Split-Path $slnPath.FullName

Compress-Archive -Path $folder\* -DestinationPath $(System.DefaultWorkingDirectory)\FunctionalTests\SampleEchoBot.zip
```
3- Configure one **_Azure CLI Task_** to:
- Run _az deployment create_ command to **create the resources** in Azure.
- Run _az webapp deployment_ command to **deploy the EchoBot** sample.
- Run _az bot direcline create_ command to **connect the bot to the DirectLine** channel

image

The output goes into a json file from where we will recover the channel key later.

The script is:
```powershell
call az deployment create --name "nightly-test-bot" --template-file "$(System.DefaultWorkingDirectory)\FunctionalTests\ExportedTemplate\template.json" --location "westus" --parameters appId=$(AppId) appSecret="$(AppSecret)" botId="$(BotName)" botSku=F0 newAppServicePlanName="$(BotName)" newWebAppName="$(BotName)" groupName="nightly-test-bot" groupLocation="westus" newAppServicePlanLocation="westus"

call az webapp deployment source config-zip --resource-group "nightly-test-bot" --name "$(BotName)" --src "$(System.DefaultWorkingDirectory)\FunctionalTests\SampleEchoBot.zip" 

call az bot directline create -n "$(BotName)" -g "nightly-test-bot" > "$(System.DefaultWorkingDirectory)\DirectLineCreate.json"
```
4- Add a new **_PowerShell Script Task_** to read the json file generated in the previous step and get the secret key to connect to the bot. It also sets an environment variable with this value.

image

The script is:
```powershell
$json = Get-Content '$(System.DefaultWorkingDirectory)\DirectLineCreate.json' | Out-String | ConvertFrom-Json

$key = $json.properties.properties.sites.key
$botName = $(BotName)

echo "##vso[task.setvariable variable=DIRECTLINE;]$key"
echo "##vso[task.setvariable variable=BOTID;]$botName"
```
5- After the Tests run, add a new **_Azure CLI Task_** to delete the resource group we've created in the first step.
image
The script is:
```powershell
call az group delete -n "nightly-test-bot" --yes
```

We strongly recommend setting this task to run _Even if a previous task has failed, even if the build was canceled_. With this setting, we will assure that the resources will be deleted from Azure even if the build fails at any step.

After running these steps, the Bot is deployed, tested and deleted.
image
image

### CODE REVIEW

**Comment by cleemullins** [comment]
```
No issues found in Microsoft.Bot.Builder.dll
No issues found in Microsoft.Bot.Builder.AI.Luis.dll
No issues found in Microsoft.Bot.Builder.AI.QnA.dll
No issues found in Microsoft.Bot.Builder.ApplicationInsights.dll
No issues found in Microsoft.Bot.Builder.Azure.dll
No issues found in Microsoft.Bot.Builder.Dialogs.dll
No issues found in Microsoft.Bot.Builder.TemplateManager.dll
No issues found in Microsoft.Bot.Configuration.dll
No issues found in Microsoft.Bot.Connector.dll
No issues found in Microsoft.Bot.Schema.dll

```

**Comment by cleemullins** [comment]
```
No issues found in Microsoft.Bot.Builder.dll
No issues found in Microsoft.Bot.Builder.AI.Luis.dll
No issues found in Microsoft.Bot.Builder.AI.QnA.dll
No issues found in Microsoft.Bot.Builder.ApplicationInsights.dll
No issues found in Microsoft.Bot.Builder.Azure.dll
No issues found in Microsoft.Bot.Builder.Dialogs.dll
No issues found in Microsoft.Bot.Builder.TemplateManager.dll
No issues found in Microsoft.Bot.Configuration.dll
No issues found in Microsoft.Bot.Connector.dll
No issues found in Microsoft.Bot.Schema.dll

```

**Comment by cleemullins** [comment]
```
No issues found in Microsoft.Bot.Builder.dll
No issues found in Microsoft.Bot.Builder.AI.Luis.dll
No issues found in Microsoft.Bot.Builder.AI.QnA.dll
No issues found in Microsoft.Bot.Builder.ApplicationInsights.dll
No issues found in Microsoft.Bot.Builder.Azure.dll
No issues found in Microsoft.Bot.Builder.Dialogs.dll
No issues found in Microsoft.Bot.Builder.TemplateManager.dll
No issues found in Microsoft.Bot.Configuration.dll
No issues found in Microsoft.Bot.Connector.dll
No issues found in Microsoft.Bot.Schema.dll

```

**Comment by fuselabs** [comment]
```
No issues found in Microsoft.Bot.Builder.dll
No issues found in Microsoft.Bot.Builder.AI.Luis.dll
No issues found in Microsoft.Bot.Builder.AI.QnA.dll
No issues found in Microsoft.Bot.Builder.ApplicationInsights.dll
No issues found in Microsoft.Bot.Builder.Azure.dll
No issues found in Microsoft.Bot.Builder.Dialogs.dll
No issues found in Microsoft.Bot.Builder.TemplateManager.dll
No issues found in Microsoft.Bot.Configuration.dll
No issues found in Microsoft.Bot.Connector.dll
No issues found in Microsoft.Bot.Schema.dll

```

**Comment by ceciliaavila** [comment]
Replaced by PR #1807

**Pull request closed without merging**
