### PR TITLE
[Expression] Loose `substring` and `subArray` restriction to accept arbitrary digital input 

### PR DESCRIPTION
**Pull request by Danieladu**
Fixes https://github.com/microsoft/botbuilder-js/issues/3616

## Description 
Loose the restriction of built-in function `substring` and `subArray` to accept arbitrary digital input instead of throw exception.

For example:
Originally:
```
substring('abc',  -1, 1)  => error, start index is < 0
substring('abc', 1, -1) => error, length is < 0
substring('abc', 1, 5) => error, length is out of range

subArray([1], -1, 1) => error, start index is < 0
subArray([1], 2, -1) => error, start index is out of range
subArray([1], 1, 5) => error, end index is out of range
```

Now:
```
substring('abc',  -1, 1)  => 'a'
substring('abc', 1, -1) => ''
substring('abc', 1, 5) => 'abc'

subArray([1], -1, 1) => [1]
subArray([1], 2, -1) => []
subArray([1], 1, 5) => []
```

## discuss
We could discuss should the "negative number" present "indicate an offset from the end of the array/string".

### CODE REVIEW

**Comment by Danieladu** [comment]
@chrimc62 Could you take a look, and make sure the solution is what you mentioned in the issue. Thanks.

**Review by boydc2014 — APPROVED** [review]

**Comment by chrimc62** [comment]
This feels a little aggressive to me.  I was using an array to control recursion and to pop-off the first element I would do: subArray(array, 1, count()) which should result in an empty array [] like in C# when there is a single element in the array.  This is a special case where start=end and since end is allowed to be "off the array by 1", start should be allowed to be equal to that.

---
In reply to: [827328498](https://github.com/microsoft/botbuilder-dotnet/pull/5540#issuecomment-827328498) [](http://example.com/codeflow?ancestors=827328498,827328498)

**Review by chrimc62 — CHANGES_REQUESTED** [review]
:clock1:

**Comment by Danieladu** [comment]
> This feels too aggressive and the bug is in JS, not C#. I was using an array to control recursion and to pop-off the first element I would do: subArray(array, 1, count()) which should result in an empty array [] like in C# when there is a single element in the array. This is a special case where start=end and since end is allowed to be "off the array by 1", start should be allowed to be equal to that so that you end up with an empty array. For other indices I think you should still return an error. I updated the original bug to more clearly describe the issue.
> 
> In reply to: [827328498](https://github.com/microsoft/botbuilder-dotnet/pull/5540#issuecomment-827328498)

I understand the requirement now. But for the expression, `subArray(array, 1, count(array))`, if the array is empty, it still would throw exception. That's right?

**Comment by Danieladu** [comment]
I would try to create a PR in js library to show what you need. Thanks.

**Comment by chrimc62** [comment]
Yes, subArray([], 1, 1) should return an error.  subArray([], 0, 0) should be OK.

**Pull request closed without merging**
