### PR TITLE
make settings immutable

### LINKED ISSUE #4722: settings memory scope is mutable
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?q=is%3Aissue+is%3Aopen++label%3Afeature-request+) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**

It should be readonly https://github.com/microsoft/botbuilder-dotnet/blob/a8acd75d79a7d8c4f0ad248e727bb2da3982e416/libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/SettingsMemoryScope.cs#L61
But it could be changed within current turn which may confuse user.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by xieofxie**
Fixes #4722

## Specific Changes

  - make settings memory scope immutable
  - update test
  - fix CustomizedMemory

### CODE REVIEW

**Comment by stevengum** [comment]
This reads like a breaking change, is it @xieofxie?

**Comment by xieofxie** [comment]
@stevengum yes.. However I would think that being able to change settings memory scope is a bug

**Comment by EricDahlvang** [comment]
I'm sorry @xieofxie I do not understand exactly how this addresses https://github.com/microsoft/botbuilder-dotnet/issues/4722 

Please explain in more detail.

Also, are there any performance implications with this change?

**Review by tomlm — APPROVED** [review]
:shipit:

**Comment by xieofxie** [comment]
@EricDahlvang Currently, when we construct TurnState, SettingsMemoryScope will return a Dictionary which is mutable (i.e. user could change it via SetProperty action).
However, this change will not persist in a new turn which causes confusion and a mutable settings scope violates its purpose.

So I change Dictionary to ImmutableDictionary to make sure it is not changed by accident as the test case indicates. (However, I don't feel very well as it is an internal exception not one set by us)

**Review by mrivera-ms — APPROVED** [review]

**Review by chrimc62 — APPROVED** [review]
:shipit:

**Review by luhan2017 — APPROVED** [review]

**Comment by xieofxie** [comment]
This needs one more code owner approval.. Thanks!

**Review by EricDahlvang — APPROVED** [review]

**Comment by xieofxie** [comment]
hmm.. sadly, it is this one microsoft/bf-dialogs
image

**Pull request merged**
