### PR TITLE
Added Slack View UI component to the payload and support for setting request header content type

### PR DESCRIPTION
**Pull request by sandeepna2206**
1. Support for Slack Views component in SlackPayload.
2. Support for selected option property in SlackAction class for static and multi_static slack UI elements.
3. Option to set http Content-type in header in client code in case the client wants to send other than "text/plain" as required by Slack Api.

### CODE REVIEW

**Comment by sandeepna2206** [comment]
Hi Tom, Can you please mention what changes are required for approval ?

**Comment by garypretty** [comment]
@sandeepna2206  Thank you very much for your contribution here.  I am going to hold off on merging this, even once the requested change has been made as I am currently reviewing the underlying client being used by the adapter and if we might swap this out for another.  This is because we have a growing number of Slack model classes in our adapter, in addition to those model classes within the client currently being used - this is because the client does not appear to be kept up to date with the change within the Slack API.  I am exploring an alternative that might include the changes required for selection options / modal etc.

I will report back once my analysis has been completed.

**Comment by garypretty** [comment]
Based on current thinking work to merge this PR will happen over the next 2 weeks and the PR will make it into R10.  We have an overlapping PR #3537 which I will work to consolidate.

**Comment by sandeepna2206** [comment]
Thanks for the update @garypretty . Looking forward for R10 to see these changes.

**Comment by garypretty** [comment]
There is now an open PR (just awaiting some resolution of failing tests) which implements some changes to the Slack adapter, including those within this PR. @sandeepna2206, thank you very much for your contribution here.

The changes in the PR, which consolidates a number of changes, also removes the tight dependency on the Slack client that was being used.  Now, a developer can install and use any client they wish directly from NuGet.

You can see the PR at https://github.com/microsoft/botbuilder-dotnet/pull/4046.  Please let me know if you have any questions.

I am going to close out this PR, but once the consolidated PR has been merged, this will be available in the nightly builds.

**Pull request closed without merging**
