### PR TITLE
Test project using .transcript files

### PR DESCRIPTION
**Pull request by enzocanoo**
We added a new project called `Microsoft.Bot.Builder.Transcripts.Tests` that contains a set of tests for each `Microsoft.Bot.Builder` package using transcript files as input.

Currently, the transcript files are located in the `.\transcripts` folder. In parallel, we are working on another approach to move the `.chat` files to a different repository and download and convert them on-the-fly to be used in the test project.

### CODE REVIEW

**Comment by cleemullins** [comment]
@JuanAr The build isn't passing. Is that due to the test changes? The build errors are all coming from the LUIS Middleware tests.

**Comment by JuanAr** [comment]
@cleemullins can you email us the VSTS error? All new tests are passing locally .

**Comment by JuanAr** [comment]
We rebased this branch on top of ` master` and fixed the tests impacted by changes in Prompts (namespaces and options.Speak new feature)

**Comment by cleemullins** [comment]
@JuanAr Could you rebase this? There are merge conflicts that need to be resolved.

**Comment by JuanAr** [comment]
Rebased!

**Comment by cleemullins** [comment]
And for QnA Maker:
2018-05-30T01:26:33.4275104Z  Test method Microsoft.Bot.Builder.Ai.QnA.Tests.QnaMakerMiddlewareTests.QnaMaker_TestMiddleware_NoResults threw exception: 
2018-05-30T01:26:33.4275628Z System.AggregateException: One or more errors occurred. (One or more errors occurred. (Assert.AreEqual failed. Expected:<https://www.qnamaker.ai/schemas/trace>. Actual:<(null)>. )) ---> System.AggregateException: One or more errors occurred. (Assert.AreEqual failed. Expected:<https://www.qnamaker.ai/schemas/trace>. Actual:<(null)>. ) ---> Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Assert.AreEqual failed. Expected:<https://www.qnamaker.ai/schemas/trace>. Actual:<(null)>. 
2018-05-30T01:26:33.4276096Z Stack Trace:
2018-05-30T01:26:33.4276384Z    at Microsoft.Bot.Builder.Ai.QnA.Tests.QnaMakerMiddlewareTests.<>c.<QnaMaker_TestMiddleware_NoResults>b__3_1(IActivity activity) in D:\a\1\s\tests\Microsoft.Bot.Builder.Ai.QnA.Tests\QnAMakerMiddlewareTests.cs:line 51
2018-05-30T01:26:33.4276763Z    at Microsoft.Bot.Builder.Adapters.TestFlow.<>c__DisplayClass12_0.<AssertReply>b__0(Task task) in D:\a\1\s\libraries\Microsoft.Bot.Builder.Core\Adapters\TestFlow.cs:line 183
2018-05-30T01:26:33.4277073Z    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
2018-05-30T01:26:33.4277316Z    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
2018-05-30T01:26:33.4277527Z --- End of inner exception stack trace ---
2018-05-30T01:26:33.4277726Z     at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
2018-05-30T01:26:33.4277971Z    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
2018-05-30T01:26:33.4278168Z    at System.Threading.Tasks.Task.Wait()
2018-05-30T01:26:33.4278426Z    at Microsoft.Bot.Builder.Adapters.TestFlow.<>c__DisplayClass7_0.<Send>b__0(Task task) in D:\a\1\s\libraries\Microsoft.Bot.Builder.Core\Adapters\TestFlow.cs:line 75
2018-05-30T01:26:33.4278686Z    at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
2018-05-30T01:26:33.4278931Z    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
2018-05-30T01:26:33.4279243Z    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
2018-05-30T01:26:33.4279753Z --- End of inner exception stack trace ---
2018-05-30T01:26:33.4280504Z     at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
2018-05-30T01:26:33.4280789Z    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
2018-05-30T01:26:33.4281015Z    at System.Threading.Tasks.Task.Wait()
2018-05-30T01:26:33.4281316Z    at Microsoft.Bot.Builder.Adapters.TestFlow.<>c__DisplayClass12_0.<AssertReply>b__0(Task task) in D:\a\1\s\libraries\Microsoft.Bot.Builder.Core\Adapters\TestFlow.cs:line 164
2018-05-30T01:26:33.4281648Z    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
2018-05-30T01:26:33.4281929Z    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
2018-05-30T01:26:33.4282168Z --- End of stack trace from previous location where exception was thrown ---
2018-05-30T01:26:33.4282528Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-05-30T01:26:33.4282783Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-05-30T01:26:33.4283146Z    at Microsoft.Bot.Builder.Ai.QnA.Tests.QnaMakerMiddlewareTests.<QnaMaker_TestMiddleware_NoResults>d__3.MoveNext() in D:\a\1\s\tests\Microsoft.Bot.Builder.Ai.QnA.Tests\QnAMakerMiddlewareTests.cs:line 43
2018-05-30T01:26:33.4283698Z --- End of stack trace from previous location where exception was thrown ---
2018-05-30T01:26:33.4283915Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-05-30T01:26:33.4284129Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by enzocanoo** [comment]
Thanks @cleemullins! We fixed the issues related to LUIS and QnA

**Comment by pcostantini** [comment]
Closing in favor of #618

**Pull request closed without merging**
