### PR TITLE
[DO NOT MERGE] Allow TextInput action to set non string property

### LINKED ISSUE #5088: TextInput action doesn't support setting non-string property
## Version
4.11.1

## Describe the bug
See a user [comment ](https://github.com/microsoft/BotFramework-Composer/issues/4875#issuecomment-753613559)here. Use TextInput to set a property with value extracted from LUIS recognized entities. If the recognized entities are an array, the TextInput action will refuse setting this array value to a property due to the string validation here https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/TextInput.cs#L51. This design seems not friendly. We think the string validation should only be applied to the raw user input rather than the property setting. Property should be able to take any valid object rather value limited to string.

## To Reproduce
1. Use TextInput action
2. Set the Property with `dialog.userInput`
3. Set the Value with an expression that returns an array, e.g. `=createArray('hello', 'world')`
4. Send a response with the `${dialog.userInput}`
5. You will see `Object reference not set to an instance of an object.`

## Expected behavior
Non-string input can be set to property

### PR DESCRIPTION
**Pull request by feich-ms**
Fixes #5088 

## Description
Remove the limitation that TextInput can only set string value to property. A more friendly solution is that TextInput only limits string format for raw user input from activity but no longer limits string format to property setting after post processing of user input. For example, users can set a luis recognized result like entity array generated from a text input to a dialog memory property. 

## Specific Changes
  - Change the input recognition and validation logic in InputDialog to allow non-string input set to property
  - Adjust the test case to test such changes

## Testing
Test case adjusted.

### CODE REVIEW

**Review by boydc2014 — APPROVED** [review]
LGTM, @tomlm do you want to take a look at this

**Comment by mrivera-ms** [comment]
@EricDahlvang, could you please review?

**Comment by EricDahlvang** [comment]
I thought TextInput should only allow Text?  Is this something we really need in the sdk?

Would AttachmentInput work to solve this issue? or a custom InputDiaog, without changes to InputDialog base class?

**Comment by feich-ms** [comment]
@EricDahlvang yes, it still only allows text from user inputs. The changes here is to allow post-processing value got from this.value expression to be any object rather than limited to string. A typical user case is LUIS recognizers can return array entities and users want to set the array to the dialog property https://github.com/microsoft/BotFramework-Composer/issues/4875#issuecomment-753613559. With current restriction of TextInput action, users cannot do that directly in TextInput action. They need to use another setProperty action to set the array entities to dialog property. @boydc2014 has a short comment here https://github.com/microsoft/botbuilder-dotnet/issues/5088#issuecomment-759887382 explaining the proposal. If we don't plan to loose the restrictions here, we can close this PR and then highlight this restriction in documentation to let users use setProperty action to set non-string values got from LUIS recognizers or any other expressions. What is your preference? @EricDahlvang @boydc2014 @mrivera-ms

**Comment by boydc2014** [comment]
> I thought TextInput should only allow Text? Is this something we really need in the sdk?
> 
> Would AttachmentInput work to solve this issue? or a custom InputDiaog, without changes to InputDialog base class?

As Fei's comments above, this change is not supposed to change the `value` of TextInput itself, but to make the post processing easier. A typical use case is as this issue https://github.com/microsoft/BotFramework-Composer/issues/4875#issuecomment-753613559. 

Whether we need this in SDK, depends on how we model the abstraction of a "InputDialog", and specifically the expectation of this "value" field. Whether
a) we think the "TextInput", "NumberInput" means the final value set to memory must be text or number,  or
b) we think the value of "TextInput", "NumberInput" must be a string or number, but **after post processing**, the memory variable eventually been set can be whatever type it is. 

I'm leaning to option b), because i feel like, that's a more natural expectation of a "post-processing" step. Putting restrictions on this post-processing feels weird.  

@Stevenic @tomlm can you share some thoughts on this?

**Comment by boydc2014** [comment]
@EricDahlvang sorry for the bothering, after checking with Fei and digged into the original code, i think this PR doesn't align with the current design, the flexibility it adds would bring more confusing than this very little convenience, so i'm closing this PR. Thanks for raising the concern.

**Pull request closed without merging**
