### PR TITLE
Set up GitHub source links for debug support

### PR DESCRIPTION
**Pull request by BruceHaley**
This sets up links to GitHub source in the symbols files. Devs can then step through source in debug sessions. Source code is downloaded on the fly as needed.

Issue #474

### CODE REVIEW

**Comment by BruceHaley** [comment]
NOW you should find only package projects with SourceLink, and no version updates. (The updates were not intended. I think someone else had updated them, and I had not merged with latest.)

**Comment by BruceHaley** [comment]
I don't plan to use parameter SourceLinkCreate=true since it is true by default. I expect SourceLinkCreate=false would be useful for suppressing SourceLink execution.

**Comment by drub0y** [comment]
Hmm, ok, 'cause I was reading [this section](https://github.com/ctaggart/SourceLink/wiki#enable-source-server-support) which says:

>You can control when it runs by setting the MSBuild property /p:SourceLinkCreate=true. That property is set to true by default on build servers that set CI or BUILD_NUMBER environment variables. In general these tools are meant to be run only on build servers.

So, maybe you don't need to set that parameter explicitly, but we would need to make sure the build is setting the `CI` or `BUILD_NUMBER` environment variables for it to happen implicitly. Not sure the VSTS build(s) have that yet, so just making sure. 😊

**Comment by cleemullins** [comment]
I confirmed the new Packages are MIT licensed. Thank Bruce!

**Pull request merged**
