### PR TITLE
Take magic code detection out of OAuth BeginDialog

### LINKED ISSUE #1596: OAuthPrompt requires user credentials when message contains guid or 6-digit number
## Version
4.3.2

## Describe the bug
The OAuthPrompt dialog is supposed to return the user token if it exists in the cache without asking for the user's credentials, according to the [documentation](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp#notes-on-the-token-retrieval-flow). This works in general, but I've noticed that whenever the user message contains either a guid or a 6-digit number, the dialog always ends up prompting the user to authenticate.

## To Reproduce
I have created a test bot with 2 dialogs: the OAuthPrompt, and a custom WaterfallDialog that calls the OAuthPrompt and them prints a success message:
```c#
dialogSet.Add(new WaterfallDialog("dialog1", GetDialog1Steps()));
dialogSet.Add(new OAuthPrompt("oauth", new OAuthPromptSettings {
    ConnectionName = "graph",
    Title = "Provide Authorization"
}));

private WaterfallStep[] GetDialog1Steps() 
{
    return new WaterfallStep[] 
    {
        (context, ct) => 
        {
            return context.BeginDialogAsync(
                "oauth",
                new PromptOptions {
                    Prompt = MessageFactory.Text(
                        "Before I can perform this operation, I " +
                            "need permission to validate your identity"
                    ),
                    RetryPrompt = MessageFactory.Text("Please finish authenticating"),
                },
                cancellationToken: ct
            );
        },
        async (context, ct) => 
        {
            await context.Context.SendActivityAsync("Authenticated!");
            return await context.EndDialogAsync(cancellationToken: ct);
        }
    };
}
```

The bot's `OnTurnAsync` simply starts `dialog1` when it receives an activity:
```c#
public async Task OnTurnAsync(ITurnContext turnContext, CancellationToken ct)
{
    var dialogContext = await this.dialogSet.CreateContextAsync(turnContext, ct);
    var result = await dialogContext.ContinueDialogAsync(ct);

    if (result.Status == DialogTurnStatus.Empty) 
    {
        if(!string.IsNullOrEmpty(turnContext.Activity.Text)) {
            await dialogContext.BeginDialogAsync("dialog1");
        }
    }
}
```

This is a sample interaction with this bot using the emulator:
image

Describing what happens here:
1. I send a `hello` message, and the bot triggers the sign in card. I click on it, type my credentials and paste the code in the chat. The bot then says I'm authenticated;
2. Sending another message (`hello again`) results in the bot saying I'm authenticated right away without promptiong for credentials, which is expected;
3. The same happens in the next message, where I send a 3-digit number;
4. However, sending a message with a 6-digit number results in the bot prompting for my credentials again. 

## Expected behavior
On step 4 above, the OAuthPrompt should not ask the user for credentials, since they are supposed to be cached.

## Additional context
~It is also possible to trigger this behavior by sending a message with a guid.~

[UPDATE 2019-04-10] I didn't mention this originally, but I'm using AADv2 as the credential provider, registered to an application account.

[UPDATE 2019-04-22] ~I've just found out that now all guids trigger the auth prompt.~

[UPDATE 2019-05-24] Removing mention to guids, since the root cause is the 6-digit number (and some guids happen to have it)

[bug]

### PR DESCRIPTION
**Pull request by mdrichardson**
Fixes #1596 

Also related: https://stackoverflow.com/questions/55970661/ms-bot-framework-doesnt-remember-authentication/55975228#55975228 - this seems like a pretty easy issue to run into.

## Issue Summary

`OAuthPrompt` has to be called to for certain messages. If that message contains a string that has a 6-digit number, `OAuthPrompt` used that number as the magic code, which was invalid, so it re-prompted for Login. The JS SDK doesn't have this issue because [it doesn't check for the magic code in `beginDialog()`](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-dialogs/src/prompts/oauthPrompt.ts#L198)
.

## Changes

* Removes attempt to detect magic code in `BeginDialogAsync()`
* Removes some other checks in `GetUserTokenAsync()` that are unnecessary because of the above change that are handled elsewhere

## Important Notes

* I couldn't really get the Auth Sample (18) on `master` to work well with or without this change. The `samples-work-in-progress` sample works fine now.
* Neither sample worked in Teams -- I'm not sure if they ever did. the Login button pops up and then nothing happens after clicking it.
* I rarely use Auth, so a review to make sure this wouldn't break something I'm missing would be much appreciated
* As you might gather by looking through my commits, I think some code duplication can be avoided by making more calls to `OAuthPrompt.GetUserTokenAsync()`. @fuselabs was throwing errors when I attempted to do this, however, since it required adding `, string code = null` to the `GetUserTokenAsync()` arguments (which would make it match the Node version). 

## Testing

image

These are using the `samples-work-in-progress` branch:

### Before

image

### After

image

### CODE REVIEW

**Comment by fuselabs** [comment]
```
No issues found in Microsoft.Bot.Builder.dll
No issues found in Microsoft.Bot.Builder.AI.Luis.dll
No issues found in Microsoft.Bot.Builder.AI.QnA.dll
No issues found in Microsoft.Bot.Builder.ApplicationInsights.dll
No issues found in Microsoft.Bot.Builder.Azure.dll
Compat issues with assembly Microsoft.Bot.Builder.Dialogs:
MembersMustExist : Member 'Microsoft.Bot.Builder.Dialogs.OAuthPrompt.GetUserTokenAsync(Microsoft.Bot.Builder.ITurnContext, System.Threading.CancellationToken)' does not exist in the implementation but it does exist in the contract.

No issues found in Microsoft.Bot.Builder.TemplateManager.dll
No issues found in Microsoft.Bot.Configuration.dll
No issues found in Microsoft.Bot.Connector.dll
No issues found in Microsoft.Bot.Schema.dll

```

**Comment by fuselabs** [comment]
```
No issues found in Microsoft.Bot.Builder.dll
No issues found in Microsoft.Bot.Builder.AI.Luis.dll
No issues found in Microsoft.Bot.Builder.AI.QnA.dll
No issues found in Microsoft.Bot.Builder.ApplicationInsights.dll
No issues found in Microsoft.Bot.Builder.Azure.dll
Compat issues with assembly Microsoft.Bot.Builder.Dialogs:
MembersMustExist : Member 'Microsoft.Bot.Builder.Dialogs.OAuthPrompt.GetUserTokenAsync(Microsoft.Bot.Builder.ITurnContext, System.Threading.CancellationToken)' does not exist in the implementation but it does exist in the contract.

No issues found in Microsoft.Bot.Builder.TemplateManager.dll
No issues found in Microsoft.Bot.Configuration.dll
No issues found in Microsoft.Bot.Connector.dll
No issues found in Microsoft.Bot.Schema.dll

```

**Comment by fuselabs** [comment]
```
No issues found in Microsoft.Bot.Builder.dll
No issues found in Microsoft.Bot.Builder.AI.Luis.dll
No issues found in Microsoft.Bot.Builder.AI.QnA.dll
No issues found in Microsoft.Bot.Builder.ApplicationInsights.dll
No issues found in Microsoft.Bot.Builder.Azure.dll
No issues found in Microsoft.Bot.Builder.Dialogs.dll
No issues found in Microsoft.Bot.Builder.TemplateManager.dll
No issues found in Microsoft.Bot.Configuration.dll
No issues found in Microsoft.Bot.Connector.dll
No issues found in Microsoft.Bot.Schema.dll

```

**Comment by mdrichardson** [comment]
FYI: Still working on writing tests. This was more difficult than anticipated as it took me awhile to discover that [TestAdapter returns a valid token regardless of the magic code](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs#L414) (if the userId, channelId, and connectionName are the same). This is pretty key for testing this.

**Comment by mdrichardson** [comment]
Tests complete.

With new OAuthPrompt:

image

With old OAuthPrompt:

image

**Comment by fuselabs** [comment]
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Builder.dll
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Builder.AI.Luis.dll
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Builder.AI.QnA.dll
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Builder.ApplicationInsights.dll
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Builder.Azure.dll
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Builder.Dialogs.dll
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Builder.TemplateManager.dll
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Configuration.dll
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Connector.dll
#### :heavy_check_mark: No Binary Compatibility issues for Microsoft.Bot.Schema.dll

**Comment by mdrichardson** [comment]
Note: I believe this actually bring it to parity with JS, since JS doesn't do magic code detection in BeginDialog

**Comment by fuselabs** [comment]
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.AI.Luis.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.AI.QnA.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.ApplicationInsights.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.Azure.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.Dialogs.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.TemplateManager.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Configuration.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Connector.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Schema.dll**

**Comment by mdrichardson** [comment]
Confirmed: JS SDK does not detect for magic code in [`beginDialog`](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-dialogs/src/prompts/oauthPrompt.ts#L119), which calls its own [`getUserToken`](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-dialogs/src/prompts/oauthPrompt.ts#L198), which also does attempt to detect magic codes.

`oauth_prompt` [does not exist in Python SDK](https://github.com/microsoft/botbuilder-python/tree/master/libraries/botbuilder-dialogs/botbuilder/dialogs/prompts). "Parity" would be making it exist. Related: https://github.com/microsoft/botbuilder-python/issues/183

**Pull request merged**
