### PR TITLE
Attempted fix for issue #802

### PR DESCRIPTION
**Pull request by JonathanFingold**

### CODE REVIEW

**Comment by JonathanFingold** [comment]
I'm not sure why the LUIS tests are failing, but they are completely unrelated. Also, I don't know why the QnA tests weren't failing before. We probably need better test coverage, but I'm not sure how to craft an appropriate call out to a reference QnA service.

**Comment by JonathanFingold** [comment]
@cleemullins or @daveta , can one of you take a look at this one. I'm blocked on a QnA Maker article.

**Comment by daveta** [comment]
@JonathanFingold : Ran into same bug, your fix looks good.  Can you rebase and try again?  I'll merge.

**Comment by JonathanFingold** [comment]
@daveta , Tests passed this time. Over to you.

**Comment by daveta** [comment]
Looks good, i'll merge when I get home (and after last merge completes)..

**Pull request merged**
