### PR TITLE
Add top level lazy load on LanguageGeneratorManager

### LINKED ISSUE #6116: Improve lg load performance
## Version
4.15.1

## Describe the bug
Composer bots with a large number of lg files take a long time to startup

## Expected behavior
Cold startup time for composer bots should be improved, we just attempt to load lg resources as needed while the bot executes and not at startup.

### PR DESCRIPTION
**Pull request by Danieladu**
Fixes #6116

## Description
Make  LanguageGenerators Lazy in LanguageGeneratorManager to reduce the cost of loading.

### CODE REVIEW

**Comment by Danieladu** [comment]
Another suggestion is that if we use the top level lazy, the "loadOnConstruction" parameter in "TemplateEngineLanguageGenerator.cs" could be dropped.

**Comment by Danieladu** [comment]
//TODO: We should add converter for type "MultiLanguageGenerator"

**Comment by carlosscastro** [comment]
Hello, thanks for working on this. 

Question about the approach: We know that LG loading takes a long time, which happens on the first request. The proposal here seems to be to load the LG resources in a lazy fashion. If that is the case, let's assume that we have a bot with highly connected assets. In that scenario, would loading take the same amount of time after this change? 

And in a more general sense, do you have performance benchmarks for before / after this change?

**Comment by Danieladu** [comment]
See the new pr: https://github.com/microsoft/botbuilder-dotnet/pull/6123

**Pull request closed without merging**
