### PR TITLE
Remove unused deprecated adal package

### PR DESCRIPTION
**Pull request by mit2nil**
#minor

### CODE REVIEW

**Comment by tracyboehrer** [comment]
We're going to hold on this.  There are other alerts coming from the affected test project.  This shouldn't not effect anyone consuming BF SDK packages as it's not published as a dependency.  It exists only to run unit tests for the Connector package.  There is another effort underway to correct this project though.

**Comment by ceciliaavila** [comment]
Hi @tracyboehrer, this PR should solve the compliance blocker in _Microsoft.Bot.Connector.Tests_. We reviewed the rest of the project and there are no more references to ADAL.
Thanks.

**Comment by tracyboehrer** [comment]
@ceciliaavila There is also an alert related to Microsoft.Rest.ClientRuntime.Azure.TestFramework

**Comment by tracyboehrer** [comment]
This was resolved in: https://github.com/microsoft/botbuilder-dotnet/pull/6690

**Pull request closed without merging**
