### PR TITLE
[#6018] Move Dotnet generators from Samples to "generators" - dotnet-templates - Echo Bot

### PR DESCRIPTION
**Pull request by ceciliaavila**
Addresses #6018
#minor

## Description
This PR adds the dotnet-templates' **Echo bot** from the [BotBuider-Samples](https://github.com/microsoft/BotBuilder-Samples/tree/main/generators/dotnet-templates) repository.
It also includes the root documentation for the dotnet-templates folder.

### Detailed Changes
- Added HOW_TO_VERSION, LICENSE, and README docs.
- Added generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot.
- Fixed some StyeCop issues in the code.

## Testing
These images show the dotnet-template working.
image

### CODE REVIEW

**Comment by ceciliaavila** [comment]
Hi @BruceHaley, this is the first PR of the series to move the dotnet generators from BotBuilder-Samples. Please let us know if you have any questions.
Thanks!

**Review by mrivera-ms — COMMENTED** [review]
Are we missing launchSettings.json?

**Comment by ceciliaavila** [comment]
> Are we missing launchSettings.json?

Hi @mrivera-ms, you're right, it was missing. I haven't noticed that it was excluded by the `.gitignore` file.
Thanks!

**Review by mrivera-ms — APPROVED** [review]

**Pull request merged**
