### PR TITLE
[#6368] SDK uses deprecated Microsoft.Azure.DocumentDB.Core library

### LINKED ISSUE #6368: SDK uses deprecated Microsoft.Azure.DocumentDB.Core library
## Version
4.16.1

## Describe the bug
The SDK uses a deprecated version of Microsoft.Azure.DocumentDb.Core which is now causing security warnings due to the lack of support for this library. Migration to Cosmos Db.NET V3 is the recommended path forward: [Migrate your application to use the Azure Cosmos DB .NET SDK v3](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/migrate-dotnet-v3?tabs=dotnet-v3).

## Expected behavior
SDK uses supported underlying libraries.

**Note:** this fix should be checked for PVA compat

### PR DESCRIPTION
**Pull request by ceciliaavila**
Fixes #6368

**Note: This PR introduces breaking changes by removing deprecated classes in Bot.Builder.Azure (see [comment](https://github.com/microsoft/botbuilder-dotnet/issues/6368#issuecomment-1160868279)).**

**The Compat check will fail for this library (You can skip it from the checks by adding the classes' names to the pipeline variable _ApiCompatExcludeClasses_ following this structure: [Package]+[Class] (_e.g.: Microsoft.Bot.Builder.Azure.CosmosDbStorage_)).**

## Description
This PR removes the deprecated package `Microsoft.Azure.DocumentDB.Core` from _Microsoft.Bot.Builder.Azure_ project along with the deprecated _CosmosDbStorage_ classes that used it to avoid security warnings due to the lack of support for this library.

## Specific Changes
  - Removed deprecated **_Microsoft.Azure.DocumentDB.Core_** from Microsoft.Bot.Builder.Azure project.
  - Removed deprecated classes: **_CosmosDbStorage_**, **_CosmosSbCustomClientOptions_**, and **_CosmosDbStorageOptions_**.
  - Removed test class **_CosmosDbStorageTests_**.

## Testing
This image shows the unit tests passing after the changes.
image

### CODE REVIEW

**Comment by BruceHaley** [comment]
:x: 3 Binary Compatibility issues for **Microsoft.Bot.Builder.Azure** compared against [version 4.6.3](https://www.nuget.org/packages/Microsoft.Bot.Builder.Azure/4.6.3).
<details>

```
TypesMustExist : Type 'Microsoft.Bot.Builder.Azure.CosmosDbCustomClientOptions' does not exist in the implementation but it does exist in the contract.
TypesMustExist : Type 'Microsoft.Bot.Builder.Azure.CosmosDbStorage' does not exist in the implementation but it does exist in the contract.
TypesMustExist : Type 'Microsoft.Bot.Builder.Azure.CosmosDbStorageOptions' does not exist in the implementation but it does exist in the contract.
```

</details>

**Comment by BruceHaley** [comment]
:x: 3 Binary Compatibility issues for **Microsoft.Bot.Builder.Azure** compared against [version 4.6.3](https://www.nuget.org/packages/Microsoft.Bot.Builder.Azure/4.6.3).
<details>

```
TypesMustExist : Type 'Microsoft.Bot.Builder.Azure.CosmosDbCustomClientOptions' does not exist in the implementation but it does exist in the contract.
TypesMustExist : Type 'Microsoft.Bot.Builder.Azure.CosmosDbStorage' does not exist in the implementation but it does exist in the contract.
TypesMustExist : Type 'Microsoft.Bot.Builder.Azure.CosmosDbStorageOptions' does not exist in the implementation but it does exist in the contract.
```

</details>

**Review by EricDahlvang — APPROVED** [review]

**Comment by BruceHaley** [comment]
:x: 3 Binary Compatibility issues for **Microsoft.Bot.Builder.Azure** compared against [version 4.6.3](https://www.nuget.org/packages/Microsoft.Bot.Builder.Azure/4.6.3).
<details>

```
TypesMustExist : Type 'Microsoft.Bot.Builder.Azure.CosmosDbCustomClientOptions' does not exist in the implementation but it does exist in the contract.
TypesMustExist : Type 'Microsoft.Bot.Builder.Azure.CosmosDbStorage' does not exist in the implementation but it does exist in the contract.
TypesMustExist : Type 'Microsoft.Bot.Builder.Azure.CosmosDbStorageOptions' does not exist in the implementation but it does exist in the contract.
```

</details>

**Comment by BruceHaley** [comment]
:x: 3 Binary Compatibility issues for **Microsoft.Bot.Builder.Azure** compared against [version 4.6.3](https://www.nuget.org/packages/Microsoft.Bot.Builder.Azure/4.6.3).
<details>

```
TypesMustExist : Type 'Microsoft.Bot.Builder.Azure.CosmosDbCustomClientOptions' does not exist in the implementation but it does exist in the contract.
TypesMustExist : Type 'Microsoft.Bot.Builder.Azure.CosmosDbStorage' does not exist in the implementation but it does exist in the contract.
TypesMustExist : Type 'Microsoft.Bot.Builder.Azure.CosmosDbStorageOptions' does not exist in the implementation but it does exist in the contract.
```

</details>

**Comment by BruceHaley** [comment]
:x: 3 Binary Compatibility issues for **Microsoft.Bot.Builder.Azure** compared against [version 4.6.3](https://www.nuget.org/packages/Microsoft.Bot.Builder.Azure/4.6.3).
<details>

```
TypesMustExist : Type 'Microsoft.Bot.Builder.Azure.CosmosDbCustomClientOptions' does not exist in the implementation but it does exist in the contract.
TypesMustExist : Type 'Microsoft.Bot.Builder.Azure.CosmosDbStorage' does not exist in the implementation but it does exist in the contract.
TypesMustExist : Type 'Microsoft.Bot.Builder.Azure.CosmosDbStorageOptions' does not exist in the implementation but it does exist in the contract.
```

</details>

**Comment by BruceHaley** [comment]
:x: 1 Binary Compatibility issues for **Microsoft.Bot.Builder.Azure** compared against [version 4.6.3](https://www.nuget.org/packages/Microsoft.Bot.Builder.Azure/4.6.3).
<details>

```
TypesMustExist : Type 'Microsoft.Bot.Builder.Azure.CosmosDbCustomClientOptions' does not exist in the implementation but it does exist in the contract.
```

</details>

**Comment by BruceHaley** [comment]
:x: 1 Binary Compatibility issues for **Microsoft.Bot.Builder.Azure** compared against [version 4.6.3](https://www.nuget.org/packages/Microsoft.Bot.Builder.Azure/4.6.3).
<details>

```
TypesMustExist : Type 'Microsoft.Bot.Builder.Azure.CosmosDbCustomClientOptions' does not exist in the implementation but it does exist in the contract.
```

</details>

**Comment by BruceHaley** [comment]
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.Azure** compared against [version 4.6.3](https://www.nuget.org/packages/Microsoft.Bot.Builder.Azure/4.6.3).

**Pull request merged**
