### PR TITLE
[DO NOT MERGE] Rename the property name to "RealId"

### PR DESCRIPTION
**Pull request by tony-xia**

### CODE REVIEW

**Comment by cleemullins** [comment]
Could you file an Issue for this? I don't think we can take this change, as it would be breaking. 

... but if you file the issue, we'll triage it and the group can look and decide the best way forward.

**Comment by cleemullins** [comment]
DO NOT MERGE - this would be a breaking change to everyone using CosmosDB provider.

**Comment by tony-xia** [comment]
@cleemullins I think the renamed property belongs to [DocumentStoreItem](https://github.com/Microsoft/botbuilder-dotnet/pull/1788/files#diff-c644fd4ca2f75b1803ef70740783fdb9L369) which is a private class. So i guess the people using CosmosDB provider should not be impacted. Please feel free to correct me if I got any misunderstanding. Thanks

**Comment by tony-xia** [comment]
and the name in JsonProperty attribute is not changed, which means the serialized json is kept unchanged.

**Comment by cleemullins** [comment]
Hi @tony-xia - I looked at this in more depth today, and you're correct. This is a private class, and it could be changed w/o breaking compat. 

However... I'm *very* risk adverse to making changes to anything having to do with stored serialized state, as it's so very hard to get right even with rigorous testing. 

My vote is to leave this "as-is". I've added a detailed comment in the code saying "Don't fix this typo", that you can see here:
https://github.com/microsoft/botbuilder-dotnet/pull/2021

**Pull request closed without merging**
