### PR TITLE
ASP.NET Integration API Documentation Comments

### PR DESCRIPTION
**Pull request by drub0y**
Adds documentation comments on both the ASP.NET Core and WebAPI integration APIs.

### CODE REVIEW

**Comment by JonathanFingold** [comment]
@drub0y looks good. Stylistically, I prefer to use descriptive text when referring to property types or return values, etc. Given the way the documentation get generated, the type information is already present. For example, a property page has the general structure:

> ## _typename_._propertyname_ Property
> ...
> _description from **summary** tag._
>     _`signature block`_
> ### Property Value
> [link to property type](#)
> ### Remarks
> _contents from the **remarks** tag._

However, having the doc XML is way better than not having it.

**Comment by JonathanFingold** [comment]
@cleemullins , please merge if you agree.

**Comment by JonathanFingold** [comment]
@drub0y I'm fine with tweaking the comments later, sometime after this PR is merged. (Part of the problem is that the documentation is fairly thin for the referenced ASP.NET types, so I may also just end up leaving these as is.)

**Comment by drub0y** [comment]
thumbs up

**Pull request merged**
