### PR TITLE
Creating HelloWorld sample based on the wiki

### PR DESCRIPTION
**Pull request by nrobert**
This is the sample HelloWorld as if it was created following the `Get started` page of the wiki

Fixes https://github.com/Microsoft/botbuilder-dotnet/issues/301

### CODE REVIEW

**Comment by cleemullins** [comment]
@nrobert, this is great. 

I do wonder though, what the value is of this sample over the EchoBot? Do you think we should update the docs to skip "Hello World" and instead go right to EchoBot? The 2 samples are so close in terms of complexity, I'm not sure there's value in having yet another "shallow" sample. 

Thoughts?

**Comment by nrobert** [comment]
Totally agree with you, we should skip one

**Comment by nrobert** [comment]
So should we change the wiki to reflect EchoBot? In that case we can forget this PR.

**Comment by cleemullins** [comment]
Based on the (almost agreed upon) list of Samples we're shortly to be creating, I'm going to close this PR out. We'll be starting fresh on samples next week.

**Pull request closed without merging**
