### PR TITLE
Updated references to latest Azure storage Nuget package

### PR DESCRIPTION
**Pull request by edboykin-insight**
References in Microsoft.Bot.Builder.Azure updated to 10.x azure storage library 
Addresses issue #1686

### CODE REVIEW

**Comment by cleemullins** [comment]
@edboykin-insight Thanks for this. We can't take it this cycle, but once 4.4 ships, we can take this change in the 4.5 cycle. Just leave this PR hanging out here for a bit longer...

**Comment by cleemullins** [comment]
Adding "Blocked" so I don't accidentally merge this until next iteration.

**Comment by GasparAcevedoZainSouthworks** [comment]
Hi @cleemullins 
These changes LGTM.

Note that is recommended to update the library _Microsoft.Azure.Storage.Blob_ to its latest version ([10.0.3](https://www.nuget.org/packages/Microsoft.Azure.Storage.Blob/)) as seven ISSUEs were solved since the v10.0.1 (one in the [v.10.0.2](https://github.com/Azure/azure-storage-net/blob/master/Blob/Changelog.txt#L9) and six in the [v.10.0.3](https://github.com/Azure/azure-storage-net/blob/master/Blob/Changelog.txt#L1)), but this isn't 100% necessary, so we can continue with the merge of these changes.

**Comment by cleemullins** [comment]
When I run this through our build process, I get an error from the Binary Compat library:
```
MembersMustExist : Member 'Microsoft.Bot.Builder.Azure.AzureBlobStorage..ctor(Microsoft.WindowsAzure.Storage.CloudStorageAccount, System.String)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'Microsoft.Bot.Builder.Azure.AzureBlobTranscriptStore..ctor(Microsoft.WindowsAzure.Storage.CloudStorageAccount, System.String)' does not exist in the implementation but it does exist in the contract.
```
https://github.com/microsoft/botbuilder-dotnet/pull/2071

Unless we can figure out a way to maintain compat, I don't think we can take this. I'm looking now, but am not optimistic.

**Comment by cleemullins** [comment]
I don't see a way to update these packages while maintaining code compatibility (the namespaces all changed), or binary compat (we are leaking the dependency via our interface). 

As a result of this, we'll stick with the existing version.

**Comment by hansmbakker** [comment]
@cleemullins I believe that eventually, consumers of this library also will want to the version of the storage library they (can) use, so what would you consider a better moment for this breaking change?

**Comment by hansmbakker** [comment]
@cleemullins when will you allow this to be fixed? The longer the wait, the more painful this issue becomes..

Several updates of the bot framework have been released already, I'd suggest that people who want to use an up-to-date bot framework would want an up-to-date storage sdk as well.

**Pull request closed without merging**
