### PR TITLE
Fix dialog id is not default set to resource id issue when LoadType = AdaptiveDialog

### LINKED ISSUE #4821: Main AdaptiveDialog dialog has an id "AdaptiveDialog" instead of resource.Id
## Version
4.10.0

## Describe the bug
The Id of the dialog that is loaded with LoadType method on resource explorer is "AdaptiveDialog".

## To Reproduce
1. Have some adaptive bot without the specified Id
2. Load the dialog:
var dialog =  resourceExplorer.LoadType<AdaptiveDialog>(resource)

dialog.Id equals "AdaptiveDialog"

## Expected behavior
dialog.Id should be the same as resource.Id

The behavior should be the same as in AdaptiveComponentRegistration.cs (line 171):
                var resourceId = Path.GetFileNameWithoutExtension(schema.Id);
                var resourceType = Path.GetExtension(resourceId).TrimStart('.').ToLowerInvariant();

                // load dynamic dialogs
                switch (resourceType)
                {
                    case "dialog":
                        // register foo.dialog as $kind
                        yield return new DeclarativeType<DynamicBeginDialog>(resourceId) { CustomDeserializer = new DynamicBeginDialogDeserializer(resourceExplorer, resourceId) };
                        break;
                }

### PR DESCRIPTION
**Pull request by feich-ms**
Fixes #4821

## Description
Set resource id as the default dialog id in loaded dialog memory when the id is not specified in dialog definition

## Specific Changes
- Change AutoAssignId function in ResourceExplorer.cs to assign id to loaded dialog json token

## Testing
Unit test is added in ResourceTests.cs

### CODE REVIEW

**Comment by EricDahlvang** [comment]
Is this backwards compatible, with existing declarative bots and their persisted dialog stack state?  Or, is this a breaking change?

**Comment by feich-ms** [comment]
@EricDahlvang, there are no impacts to existing bot and dialog stack state I think. The only impact caused by the changes here is that the EndPoint of the Source for the loaded dialogs will be one line larger than dialogs definied in disk, but this only happens to those dialogs that don't have id specifically defined in dialog file. The above change is adding the missing id token to the loaded dialog json object. Feel free to let me know if you have any concerns.

**Comment by carlosscastro** [comment]
Just got back to office from leave, checking this PR shortly.

**Comment by mrivera-ms** [comment]
@carlosscastro, please review this when you have a moment. Thank you.

**Comment by mrivera-ms** [comment]
@carlosscastro,  please review this when you have a moment. Thank you.

**Comment by carlosscastro** [comment]
@mrivera-ms working on this one. Just to clarify: what I need to do here is not jsut review, but get this branch under the debugger and make sure all things are good. These lines number details can break debugging and other delicate scenarios so I want to take the extra time to assess. Trying to get this in by 1/29

**Comment by carlosscastro** [comment]
Actually did the testing and all worked in the first try. Note that for all things to be happy, we need this PR + https://github.com/microsoft/botbuilder-dotnet/pull/5072 which fix a bunch of small issues in related areas.

Thanks for ther work @feich-ms , I know this probably was tough to debug!

**Review by carlosscastro — APPROVED** [review]

**Pull request merged**
