### PR TITLE
[#5688] Drop .Net Core 2.1 support to follow the officially supported versions

### LINKED ISSUE #5688: Drop .Net Core 2.1 support to follow the officially supported versions
In August 2021, .Net core 2.1 is no longer supported. Maintain the SDK on supported versions of .Net. 

@mrivera-ms  Please update this issue to include the officially supported list of version and support dates. :)

### PR DESCRIPTION
**Pull request by ceciliaavila**
Fixes #5688

## Description
This PR removes NetCore 2.1 from the project and updates the CI pipelines' yamls to stop building and testing the projects for this framework.

**_Note: The libraries are still targeting netstandard2.0 to keep compatibility with the projects `Microsoft.Bot.Builder.Integration.AspNet.WebApi` and `Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi` that use net476 framework._**

## Specific Changes
- Removed [Microsoft.Bot.Builder.TestBot.NetCore21](https://github.com/southworks/botbuilder-dotnet/tree/main/tests/Microsoft.Bot.Builder.TestBot.NetCore21) project from the solution.
- Removed conditions for BuildTarget = netcoreapp2.1 from the test projects.
- Updated the following yaml files to remove the steps related to NetCore2.1:
   - botbuilder-dotnet-ci-mac
   - botbuilder-dotnet-ci
   - ci-test-steps

## Testing
This image shows the CI pipeline running after the changes.
image

### CODE REVIEW

**Comment by gabog** [comment]
Hi @ceciliaavila, can you rebase this PR against the v5 branch that we just created? 

Thanks

**Comment by mrivera-ms** [comment]
Thanks @ceciliaavila for updating this PR. The target branch is showing as 'main', however. This will need to merge into the new 'v5' branch.

**Comment by ceciliaavila** [comment]
> Thanks @ceciliaavila for updating this PR. The target branch is showing as 'main', however. This will need to merge into the new 'v5' branch.

Hi @mrivera-ms, target branch updated! Thanks.

**Review by mrivera-ms — APPROVED** [review]

**Review by gabog — CHANGES_REQUESTED** [review]
Hi @ceciliaavila, I am in the process of validating this PR, will close this comment and merge if everything looks good.
Thanks

**Review by gabog — CHANGES_REQUESTED** [review]
Hi @ceciliaavila, I pulled your branch locally and opened with VSCode. Did a search for netcoreapp2.1 and I see we still have projects in the repo that reference 2.1:
 
image

Most of them seem to be in the Teams test folder that are not part of the main solution but I think we should update those remove 2.1 and **also target 3.1 instead of 3.0** (we will need to figure out what to do with all these _hidden_ tests later).

I also compiled the main solution and noticed that we have some unit tests still targeting 2.1 (I grouped test explorer by framework):

image

Can you address these as part of this PR too?
Thanks

**Comment by ceciliaavila** [comment]
Hi @gabog, the remaining references to 2.1 were removed. Thanks!

**Review by gabog — APPROVED** [review]

**Pull request merged**
