### PR TITLE
Add/handoff lib

### PR DESCRIPTION
**Pull request by arturl**
Adding APIs for initiating and acknowledging handoff to agent:

```
var msg1 = MessageFactory.Text("first message");
var msg2 = MessageFactory.Text("second message");
var transcript = new Activity[] { msg1, msg2 };
var context = new { Skill = "credit cards" };
IHandoffRequest request = await turnContext.InitiateHandoffAsync(transcript, context, cancellationToken);
```

### CODE REVIEW

**Comment by fuselabs** [comment]
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.AI.Luis.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.AI.Luis/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.AI.QnA.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.AI.QnA/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.ApplicationInsights.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.ApplicationInsights/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.Azure.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.Azure/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.Dialogs.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.Dialogs/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.TemplateManager.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.TemplateManager/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Configuration.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Configuration/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Connector.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Connector/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Schema.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Schema/4.3.1)

**Comment by johnataylor** [comment]
Just capturing the conversation from our in person review.

We should:
1) provide meaningful properties on the typed IHandoffActivity
1) extend ActivityHandler appropriately

If we are shipping this first as sample, we can follow the pattern here:

https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/46.teams-auth/TeamsActivityHandler.cs

For the time being and then move this code into the core in 4.6 (so when you do the sample open a issue on the product so we remember to do that - you can open the issue in dotnet just add a parity need label.)

Otherwise, new interface on adapter seems good to me. With the usage resembling the runtime type identification pattern from good old QueryInterface

And the extension method on TurnContext seems pretty clean to me.

**Comment by arturl** [comment]
@johnataylor: this can be done as part of the integration into the main SDK. When handoff is in a standalone library, the _existing_ `Microsoft.Bot.Schema.Activity` would have to implement a _new_ (modified) `IHandoffActivity` interface, which is not possible.

I also had to introduce a new `ActivityHandler` -- but that introduces ambiguity between this new type and the existing one in `Microsoft.Bot.Builder`. This requires disambiguation code that will have to be undone later. 

Here is my experimental implementation (compiles but doesn't work due to the first issue above)

https://github.com/microsoft/botbuilder-dotnet/commit/ca702adf0ac6e57650f4c48d35b02056968b2d82

**Comment by arturl** [comment]
Added `ActivityHandlerWithHandoff` in the sample slightly less ambitious but worked out nicely.

**Comment by fuselabs** [comment]
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.AI.Luis.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.AI.Luis/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.AI.QnA.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.AI.QnA/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.ApplicationInsights.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.ApplicationInsights/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.Azure.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.Azure/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.Dialogs.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.Dialogs/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.TemplateManager.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.TemplateManager/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Configuration.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Configuration/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Connector.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Connector/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Schema.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Schema/4.3.1)

**Comment by fuselabs** [comment]
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.AI.Luis.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.AI.Luis/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.AI.QnA.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.AI.QnA/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.ApplicationInsights.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.ApplicationInsights/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.Azure.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.Azure/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.Dialogs.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.Dialogs/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.TemplateManager.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.TemplateManager/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Configuration.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Configuration/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Connector.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Connector/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Schema.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Schema/4.3.1)

**Comment by fuselabs** [comment]
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.AI.Luis.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.AI.Luis/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.AI.QnA.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.AI.QnA/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.ApplicationInsights.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.ApplicationInsights/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.Azure.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.Azure/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.Dialogs.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.Dialogs/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.TemplateManager.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Builder.TemplateManager/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Configuration.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Configuration/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Connector.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Connector/4.3.1)
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Schema.dll** compared against [version 4.3.1](https://www.nuget.org/packages/Microsoft.Bot.Schema/4.3.1)

**Comment by mutanttech** [comment]
@arturl, I was looking at this experimental and was wondering if v4.6 will get framework level support to implement Human Hand Over scenario with specific activity type.
I had one question for you based, so basically I have implemented a v4 bot and running it on latest 4.5.1 SDK. My question is that I have to integrate a third party API to transmit the chat from AI Bot to an Agent using when user asks for it. Now with v3 it was very much feasible to keep a dialog active on the stack and keep processing the upcoming chats through it. But with V4 I am little confused, because I want the chat to route to a LiveAgentChatDialog from QnADialog based on certain condition and then all the subsequent chats/turns should get directly processed from this dialog. 
So, essentially keeping this dialog active until the control does not gets back from LiveAgent to AI Bot. Please revert soon if possible with your thoughts on same. :)

**Comment by arturl** [comment]
To @mutanttech: your scenario is known as "bot as a proxy". You can implement the message router in the middleware (or even in the bot logic, though less elegant). Each message in the conversation would be handed over to an agent hub and the response sent to the client. From the client point of view, the conversation is still taking place between it and the bot.
Contrast this with the approach proposed in this PR, in which the bot acts as one of the agents.

**Comment by mutanttech** [comment]
@arturl, Thanks for your response. I have thought about the middleware but then for now my solutions looks like below - 
I am obtaining the intent for support from a dialog and once it is established move the user to different LiveAgentChat dialog for that specific logic. The dialog does its works and ends saving the state. Next time when request comes in root dialog, I check the conversation state for a specific property and based on it redirect the conversation to the LiveAgentChat Dialog. 
When user ends the chat with Live Agent I want the control back to AI/QnA bot, so that further questions goes answered from the KB.

Let me know how does this sounds to you.

I had one more question the LiveChatAPI, I am using requires a call back hook where it can send the messages/events back from the agent, and now they want us to use it. Essentially they are sending events as Fire&Forget with a retry on failure. Thus I had to implement an eventstore (in Cosmos dB) to store events and then poll Cosmos periodically display message back to user and mark them processed. 

Is there any way to make it more real time or pus-sub kind of analogy? Thinking about multiple users having concurrent chats with 2 or more agents and then managing their events is something that's taking some time to wrap around my head to.

Please comment.

**Comment by cleemullins** [comment]
I believe this is all done and good-to-go in a seperate PR. Closig this one.

**Pull request closed without merging**
