### PR TITLE
uischema: port composer ui schema 'flow' part to component schema files

### PR DESCRIPTION
**Pull request by yeze322**
follows #4341 

## Description
In #4341, we port the ui schema `form` part to runtime in order to support the customization of Composer Form Editor;
in this PR, the `flow` part is added to runtime as well to support the customization of Composer Flow Editor.

Refs ui.schema definition change in SDK repo: https://github.com/microsoft/botframework-sdk/pull/6163

## Affected SDK $kinds
- QnAMakerDialog
- BeginDialog
- BeginSkill
- CancelAllDialog
- DeleteProperty, DeleteProperties
- EditActions
- EditArray
- EmitEvent
- Foreach, ForeachPage
- GetActivityMembers, GetConversationMembers
- HttpRequest
- IfCondition
- ReplaceDialog
- SendActivity
- SetProperties, SetProperty
- SwitchCondition
- ThrowException
- UpdateActivity
- Ask
- AttachmentInput, ChoiceInput, ConfirmInput, DateTimeInput, NumberInput, TextInput
- OAuthInput

## Example
Below is an example of the `flow` schema:
```
{
    "$schema": "https://schemas.botframework.com/schemas/ui/v1.0/ui.schema",
    "form": {...},
    "flow": {
        "widget": "ActionCard",
        "body": {
            "widget": "ResourceOperation",
            "operation": "=coalesce(action.changeType, \"?\")",
            "resource": "=coalesce(action.itemsProperty, \"?\")"
        },
        "footer": {
            "widget": "PropertyDescription",
            "property": "=action.resultProperty",
            "description": "= Result"
        },
        "hideFooter": "=!action.resultProperty"
    }
}

```
which describes the `Microsoft.EditArray` type in Composer as
image

### CODE REVIEW

**Review by a-b-r-o-w-n — CHANGES_REQUESTED** [review]
The UI schema needs to be updated to reflect all of these properties.

**Comment by chrimc62** [comment]
And also the .schema.  In particular you need to run tests and check the all-up test.schema/.uischema to make sure they have the changes you expect.

---
In reply to: [571498269](https://github.com/microsoft/botbuilder-dotnet/pull/5099#issuecomment-571498269) [](ancestors = 571498269)

**Comment by yeze322** [comment]
Updated the schema merge result.
Notes that `test.schema` is also affected because of the change of LogAction in #5036

**Review by a-b-r-o-w-n — APPROVED** [review]

**Review by chrimc62 — APPROVED** [review]
:shipit:

**Pull request merged**
