### PR TITLE
Remove unnecessary checks for null

### PR DESCRIPTION
**Pull request by flash2048**
Fixes #minor
# Description
In the code, a lot of things were checked for null twice. 
I think it will be better to clean it. 
It will improve readability and performance.

### CODE REVIEW

**Comment by BruceHaley** [comment]
Hi Andrei,
Unfortunately, required PR checks failed because the build pipelines failed to handle your fork properly.
[Our fix to the pipelines](https://github.com/microsoft/botbuilder-dotnet/pull/6259) has now been merged.
If you could do a "fetch upstream" and merge that fix into your branch, then we might get those PR checks to pass. 
Thank you, and sorry for your trouble. 
--Bruce

**Comment by flash2048** [comment]
> [BruceHaley](/BruceHaley)

Hello, I did "fetch upstream" for it.

**Comment by gabog** [comment]
Thanks for the submission @flash2048, we agree that some of null checks are unnecessary, however some of the changes you are suggesting could potentially introduce changes in behavior and they are hard to test (e.g.: changing `Value?.EvaluateExpression(dc.State);` to `Value.EvaluateExpression(dc.State);`  could potentially throw an NullReferenceException if Value is null).
We appreciate the contribution but we think it is too risky to take the PR as is at the moment without testing each feature individually and ensuring that removing the checks will not introduce bugs.

**Pull request closed without merging**
