### PR TITLE
Enable BotState to work without serializing types

### PR DESCRIPTION
**Pull request by EricDahlvang**
Fixes: https://github.com/microsoft/botbuilder-dotnet/issues/2437

and 

Fixes https://github.com/microsoft/botbuilder-dotnet/issues/2450

### CODE REVIEW

**Comment by johnataylor** [comment]
@EricDahlvang is this still a work in progress?

**Comment by EricDahlvang** [comment]
@johnataylor Looking for feedback, and hoping we can take this (or something like it) in order to allow `new JsonSerializer() { TypeNameHandling = TypeNameHandling.None })`

**Comment by tomlm** [comment]
We can't do this, it's a breaking change.

**Comment by EricDahlvang** [comment]
@tomlm The default serialization settings are the same, the change is optin.  Which part would be breaking?

**Comment by EricDahlvang** [comment]
Spoke with Tom in person, who said this would be ok as long as it is opt-in only (not breaking for existing bots which are reliant on type info).

**Comment by EricDahlvang** [comment]
Here's a separate draft without the new classes: https://github.com/microsoft/botbuilder-dotnet/pull/3023

**Comment by EricDahlvang** [comment]
Closing this one in favor of https://github.com/microsoft/botbuilder-dotnet/pull/3023

**Pull request closed without merging**
