### PR TITLE
Fix first activity from bot to user has fake replyToId value

### LINKED ISSUE #5310: First activity has fake replyToId value that is causing a bug in WebChat
When the bot sends the very first activity in a conversation, it has a random string in `replyToId`. This value refers to a an activity that does not exist.

The WebChat team needs to have this value removed.

See the original issue in the WebChat repo: [WebChat Issue 3707](https://github.com/microsoft/BotFramework-WebChat/issues/3707)

### PR DESCRIPTION
**Pull request by feich-ms**
Fixes #5310 

## Description
When the activity is the first one of the conversation and it's sent from bot to user, the ReplyToId was assigned to the bogus ConversationUpdate activity's id. The fix is to not assign the bogus ReplyToId if previous activity is the ConversationUpdate activity

## Specific Changes
  - Do not assign ReplyToId if conversantionReference is from ConversationUpdate activity
  - Add test tests to test the changes

## Testing
Tests are added

### CODE REVIEW

**Comment by boydc2014** [comment]
I saw a few places that replyToId is been assigned to, please make sure all code path is covered.

**Comment by feich-ms** [comment]
Sure, covered all possible paths and add test cases

**Review by boydc2014 — APPROVED** [review]

**Comment by boydc2014** [comment]
@mrivera-ms this looks good to me now

**Comment by EricDahlvang** [comment]
Is this underlying issue applicable to all channels?  Or only WebChat/DirectLine?

ConversationUpdate is sent by multiple channels:
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channels-reference?view=azure-bot-service-4.0#welcome

**Comment by mrivera-ms** [comment]
@compulim, are you able to answer the question posted by @EricDahlvang ?

**Comment by mrivera-ms** [comment]
@compulim, the SDK team reviewed this change and there are concerns about how this will affect backward compatibility and existing users in Composer. Can you comment on the question above?

**Comment by compulim** [comment]
> Is this underlying issue applicable to all channels? Or only WebChat/DirectLine?
> 
> ConversationUpdate is sent by multiple channels:
> https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channels-reference?view=azure-bot-service-4.0#welcome

I am not familiar with other channel. There is a probability that they don't use the `replyToId` field.

Excerpt from https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#activity-object.

> The ID of the message to which this message replies. To reply to a message that the user sent, set this property to the ID of the user's message. Not all channels support threaded replies. In these cases, the channel will ignore this property and use time ordered semantics (timestamp) to append the message to the conversation.

**Comment by compulim** [comment]
BTW, how about JavaScript SDK?

**Comment by compulim** [comment]
Ping on these two things:
- I am not familiar with other channels, such as Teams, which supports threaded replies. Wondered how it work with a bogus ID. Maybe an expert from Teams would be better to answer Eric's question
- Is the JavaScript SDK also get updated too?

**Comment by boydc2014** [comment]
Since we are not sure the impacts for other channels, the most safe way is to only fix for WebChat/DirectLine, can you check if is it possible @feich-ms? if it is, please update.

**Comment by clearab** [comment]
@EricDahlvang @johnataylor do you think this would impact the Teams channel? Alterations to the conversationReference behavior make me a bit nervous

**Comment by EricDahlvang** [comment]
It seems risky to alter the behavior for channels we are not 100% sure about.

Can we just do this for webchat and directline only?

```
this.Type != ActivityTypes.ConversationUpdate || (!string.Equals(this.ChannelId, "directline", StringComparison.OrdinalIgnoreCase) && !string.Equals(this.ChannelId, "webchat", StringComparison.OrdinalIgnoreCase)) ? this.Id : null
```

**Comment by feich-ms** [comment]
> It seems risky to alter the behavior for channels we are not 100% sure about.
> 
> Can we just do this for webchat and directline only?
> 
> ```
> !string.Equals(this.Type, ActivityTypes.ConversationUpdate, StringComparison.OrdinalIgnoreCase) || (!string.Equals(this.ChannelId, "directline", StringComparison.OrdinalIgnoreCase) && !string.Equals(this.ChannelId, "webchat", StringComparison.OrdinalIgnoreCase)) ? this.Id : null
> ```

Resolved with your suggestions

**Comment by feich-ms** [comment]
@EricDahlvang @mrivera-ms changed to only fix for directline and webchat channel so that other channels will not be affected.

**Comment by mrivera-ms** [comment]
@feich-ms, please resolve the conflicts. Thank you.

**Comment by feich-ms** [comment]
@mrivera-ms resolved. Pls let me know if there are any other issues for this PR.

**Review by johnataylor — CHANGES_REQUESTED** [review]
what exactly is this attempting to fix?

**Comment by mrivera-ms** [comment]
> what exactly is this attempting to fix?

@johnataylor, this is fixing an issue that appears as a bug in WebChat: 

When the bot sends the very first activity in a conversation, it has a random string in replyToId. This value refers to a an activity that does not exist. The WebChat team needs to have this value removed.

See the original issue in the WebChat repo: [WebChat Issue 3707](https://github.com/microsoft/BotFramework-WebChat/issues/3707)

**Review by johnataylor — APPROVED** [review]

**Pull request merged**
