### PR TITLE
Rename AdaptiveSkillDialog => BeginSkillDialog as an action

### PR DESCRIPTION
**Pull request by tomlm**
* Rename $kind Microsoft.SkillDialog => Microsoft.BeginSkillDialog
* Rename class AdaptiveSkillDialog => BeginSkillDialog
* Move files into actions folders
* replace all $kind => new $kind
* update test schema

### CODE REVIEW

**Comment by mareekuh** [comment]
"Rename $kind Microsoft.SkillDialog => Microsoft.BeginSkillDialog"

Can we please call this 'Microsoft.BeginSkill" vs SkillDIalog?
For 2 reasons:
1. Duplication and confusion prevention. Is it a skill or a dialog? I this case it's a skill, the 'remote skill' type, which is immutable. Dialogs are 'mutable' (this is the whole essence of the SDK!) so let's not merge the concepts.

2. PVA uses Topics and this is a concept that is very important to them and so far it resonates with their audience. Dialogs are 'holy' for the SKD/Composer
Skills is a mechanism for us to connect PVA and Composer. So let's please keep the terms around calling/launching a Skill as neutral as possible and not add Dialog unless absolutely necessary. Which imo it is not in this case.

@cwhitten @tomlm @sangwoohaan @cleemullins

**Comment by mareekuh** [comment]
@cwhitten - for terms and terminology, could you please include myself and VIsh as approvers as we both work on this from the SDK and Composer UX perspective?

**Comment by tomlm** [comment]
Given that half of us thought BeginSkilll was a fine name, and Marieke has put her weight strongly behind BeginSkill we are going to snap to that.  Update pending.

**Comment by mareekuh** [comment]
thank you @tomlm (-:

**Pull request merged**
