### PR TITLE
Added emulator deep links to all samples

### PR DESCRIPTION
**Pull request by tonyanziano**
- Added emulator deep links to the rest of the samples with `.bot` files included
  - (Didn't add to `Console-EchoBot` or `Luis-Dispatch`)
- Updated deep link to use `bot.open?path={BOT_FILE_PATH}` scheme instead of `livechat.open?botUrl={ENDPOINT}[&MSA_ID / MSA_PW]`

@vishwacsena The only issue with this approach is that we are now opening the `.bot` file which specifies an endpoint service with port `5000` which is not always the case when loading up the project with Visual Studio. Sometimes I'd get `localhost:19196` or `localhost:32330`, etc. which wouldn't be accessible via the bot file opened in the emulator without changing the endpoint service's port.

### CODE REVIEW

**Comment by drub0y** [comment]
Certainly reading the settings from what has been configured rather than hardcoding seems like a good idea. I actually do not surface these as something you can get access to after the initial `Configure` call at start up, but I certainly could if you think that's something that's valuable @cleemullins.

**Comment by cleemullins** [comment]
@drub0y , @tonyanziano - I think surfacing that would be quite handy, and would reduce the fragility of this quite a bit.

**Comment by tonyanziano** [comment]
Awesome! I'll get on that. Thanks @drub0y

**Comment by cleemullins** [comment]
I've merged in #595, so this should be PR should be ready to implement. Let's see if we can get this in today! :)

**Comment by tonyanziano** [comment]
@drub0y We decided that we should add ability to the protocol handler to allow endpoint property overrides. So you should be able to just append `&url=http://localhost:[VS Dynamic Port]` or `&port=[VS Dynamic Port` to the protocol URL, and it would use that instead of the one found in the `.bot` file.

This will require some work to be done first on the Emulator side, and is being tracked here:

[Emulator #602](https://github.com/Microsoft/BotFramework-Emulator/issues/602)

**Comment by cleemullins** [comment]
@tonyanziano Hey Tony - now that your emulator changes are in, are we almost ready for this one?

**Comment by cleemullins** [comment]
@tonyanziano Now that the Emulator changes are in (wohoo!) where does this PR sit?

**Comment by tonyanziano** [comment]
@drub0y , @cleemullins 

Somehow I lost permissions to this repo today, during my updates to the PR. So I had to make a fork of the repo, and push my changes to the fork and initiate a PR from there.

I also don't have permissions to tag either of you as reviewers for whatever reason.

Please refer to #694 which picks up from the last commit **504daf1**

**Pull request closed without merging**
