### PR TITLE
Added updated LUIS Sample

### PR DESCRIPTION
**Pull request by joescars**
Added bases LUIS sample with updated code. 

This addresses #306 and #313

### CODE REVIEW

**Comment by cleemullins** [comment]
@joescars , Hey Joe, is this different from the [Microsoft.Bot.Samples.AI.Luis](https://github.com/Microsoft/botbuilder-dotnet/tree/master/samples/Microsoft.Bot.Samples.Ai.Luis) 
 sample that already exists? 

At least at a glance, it seems similar. I think we only want 1 Luis sample in the Repo at this time. 

Thoughts? Should we close this out?

**Comment by cleemullins** [comment]
@joescars, looking at the existing sample, I actually like yours better. The existing sample is a mess.

**Comment by cleemullins** [comment]
@joescars, I updated the existing sample to use the latest codebase. Take a quick look at #331 and let me know if that solves the issue here. That's got all the right namespaces and other similar stuff setup.

**Comment by joescars** [comment]
@cleemullins the updated demo looks great. This definitely solves the issue. Tx!

**Pull request closed without merging**
