### PR TITLE
Fix CodeQL SM02211 alert - SerializationBinder

### LINKED ISSUE #6515: CodeQL alert SM02211: Unsafe TypeNameHandling in microsoft/microsoft/botbuilder-dotnet/botbuilder-dotnet
## Repro Steps

<b>Summary: </b><br>CodeQL detected the following issue: <b>Unsafe TypeNameHandling</b> (<a href="https://onees.lgtm.microsoft.com/rules/1001132">Help link</a>)<br><b>Repository:</b> <a href="https://github.com/microsoft/botbuilder-dotnet/blob/main?path=/libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorage.cs#L24&amp;lineStartColumn=129&amp;lineEndColumn=149">https://github.com/microsoft/botbuilder-dotnet/blob/main?path=/libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorage.cs#L24&amp;lineStartColumn=129&amp;lineEndColumn=149</a><br><b>File:</b> /libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorage.cs<br><b>Location:</b> Line 24, Column 129 - 149<br><b>Link:</b> (<a href="https://onees.lgtm.microsoft.com/issues/1011948/csharp/6ubEheE9ce58aaqs3a4vO2egbNA=">Link to LGTM</a>)<br><br><b>Recommendations:</b><br>Use of this Json.net TypeNameHandling constant is unsafe
<br>Using an unsafe TypeNameHandling constant is a security vulnerability.<br><b>Microsoft requirement(s):</b> Microsoft.Security.SystemsADM.10010;Microsoft.Security.SystemsADM.10201<br><b>Requirement:</b> CodeQL.SM02211 (<a href="https://liquid.microsoft.com/ref?_reqref=1480D06A-3EBB-45BA-BC81-D79569A7D2C1.rex:%2f%2fscanningtoolwarnings%2fRequirements%2fCodeQL.SM02211">Link to Liquid Requirement</a>)<br><b>Confidence:</b> high

## System Info

This issue is a copy of [ADO work item 77506](https://dev.azure.com/fuselabs/SDK_v4/_workitems/edit/77506) created by CodeQL.
This item was created with <b>CodeQL</b> automated bug filer from CodeQL static analysis tool (formerly known as Semmle).<br>For more information, see <a href="https://aka.ms/CodeQL">CodeQL @ Microsoft</a>.To change onboarding settings, visit <a href="https://semmleportal.azurewebsites.net">CodeQL Portal</a>.<br>To suppress, add a comment in code (see more details <a href="https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/codeql/codeql-semmle#guidance-on-suppressions">here</a>.)

### PR DESCRIPTION
**Pull request by sw-joelmut**
Fixes #6515 #6516 #6517 #6519 #6520

## Description
This PR fixes the CodeQL SM02211 alert related to unsafe `JsonSerializer` `TypeNameHandling` usage.
For these cases, it implements a custom [SerializationBinder](https://www.newtonsoft.com/json/help/html/SerializeSerializationBinder.htm), allowing only the types that are defined in the configuration or related ones.

## Specific Changes
- Adds the `AllowedTypesSerializationBinder` class to allow only types that are defined in the instance.
- Adds tests for the `AllowedTypesSerializationBinder` class.
- Updated `BlobsStorage`, `AzureBlobStorage`, and `CosmosDbPartitionedStorage` classes to implement the binder.
- Updated `BlobsTranscriptStore` setting the `TypeNameHandling` to None.

## Testing
The following image shows the tests passing successfully and the error message when a type isn't allowed by the process.
image
image

### CODE REVIEW

**Comment by tracyboehrer** [comment]
@sw-joelmut This is getting some test failures in the storage tests.  Here is one:

```[xUnit.net 00:00:46.63]     Microsoft.Bot.Builder.Azure.Tests.CosmosDbPartitionedStorageTests.WriteAsyncFailure [FAIL]
  Failed Microsoft.Bot.Builder.Azure.Tests.CosmosDbPartitionedStorageTests.WriteAsyncFailure [357 ms]
  Error Message:
   Assert.Throws() Failure
Expected: typeof(Microsoft.Azure.Cosmos.CosmosException)
Actual:   typeof(System.InvalidOperationException): Unable to find the following types in the 'AllowedTypes' collection.
  - <>f__AnonymousType0, Microsoft.Bot.Builder.Azure.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

Please provide the 'AllowedTypesSerializationBinder' in the custom 'JsonSerializerSettings' instance, with the list of types to allow.

Example:
    new JsonSerializerSettings
    {
        SerializationBinder = new AllowedTypesSerializationBinder(
            new List<Type>
            {
                typeof(<>f__AnonymousType0),
            }),
    }
---- System.InvalidOperationException : Unable to find the following types in the 'AllowedTypes' collection.
  - <>f__AnonymousType0, Microsoft.Bot.Builder.Azure.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

Please provide the 'AllowedTypesSerializationBinder' in the custom 'JsonSerializerSettings' instance, with the list of types to allow.

Example:
    new JsonSerializerSettings
    {
        SerializationBinder = new AllowedTypesSerializationBinder(
            new List<Type>
            {
                typeof(<>f__AnonymousType0),
            }),
    }
  Stack Trace:
     at Microsoft.Bot.Builder.AllowedTypesSerializationBinder.ThrowDisallowedTypesError(List`1 types) in /Users/runner/work/1/s/libraries/Microsoft.Bot.Builder/AllowedTypesSerializationBinder.cs:line 170
   at Microsoft.Bot.Builder.AllowedTypesSerializationBinder.CleanupTypes(JContainer json) in /Users/runner/work/1/s/libraries/Microsoft.Bot.Builder/AllowedTypesSerializationBinder.cs:line 148
   at Microsoft.Bot.Builder.Azure.CosmosDbPartitionedStorage.WriteAsync(IDictionary`2 changes, CancellationToken cancellationToken) in /Users/runner/work/1/s/libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorage.cs:line 220
----- Inner Stack Trace -----
   at Microsoft.Bot.Builder.AllowedTypesSerializationBinder.ThrowDisallowedTypesError(List`1 types) in /Users/runner/work/1/s/libraries/Microsoft.Bot.Builder/AllowedTypesSerializationBinder.cs:line 170
   at Microsoft.Bot.Builder.AllowedTypesSerializationBinder.CleanupTypes(JContainer json) in /Users/runner/work/1/s/libraries/Microsoft.Bot.Builder/AllowedTypesSerializationBinder.cs:line 148
   at Microsoft.Bot.Builder.Azure.CosmosDbPartitionedStorage.WriteAsync(IDictionary`2 changes, CancellationToken cancellationToken) in /Users/runner/work/1/s/libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorage.cs:line 220
```

**Comment by sw-joelmut** [comment]
> @sw-joelmut This is getting some test failures in the storage tests. Here is one:
> 
> ```
>   Failed Microsoft.Bot.Builder.Azure.Tests.CosmosDbPartitionedStorageTests.WriteAsyncFailure [357 ms]
>   Error Message:
>    Assert.Throws() Failure
> Expected: typeof(Microsoft.Azure.Cosmos.CosmosException)
> Actual:   typeof(System.InvalidOperationException): Unable to find the following types in the 'AllowedTypes' collection.
>   - <>f__AnonymousType0, Microsoft.Bot.Builder.Azure.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
> 
> Please provide the 'AllowedTypesSerializationBinder' in the custom 'JsonSerializerSettings' instance, with the list of types to allow.
> 
> Example:
>     new JsonSerializerSettings
>     {
>         SerializationBinder = new AllowedTypesSerializationBinder(
>             new List<Type>
>             {
>                 typeof(<>f__AnonymousType0),
>             }),
>     }
> ---- System.InvalidOperationException : Unable to find the following types in the 'AllowedTypes' collection.
>   - <>f__AnonymousType0, Microsoft.Bot.Builder.Azure.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
> 
> Please provide the 'AllowedTypesSerializationBinder' in the custom 'JsonSerializerSettings' instance, with the list of types to allow.
> 
> Example:
>     new JsonSerializerSettings
>     {
>         SerializationBinder = new AllowedTypesSerializationBinder(
>             new List<Type>
>             {
>                 typeof(<>f__AnonymousType0),
>             }),
>     }
>   Stack Trace:
>      at Microsoft.Bot.Builder.AllowedTypesSerializationBinder.ThrowDisallowedTypesError(List`1 types) in /Users/runner/work/1/s/libraries/Microsoft.Bot.Builder/AllowedTypesSerializationBinder.cs:line 170
>    at Microsoft.Bot.Builder.AllowedTypesSerializationBinder.CleanupTypes(JContainer json) in /Users/runner/work/1/s/libraries/Microsoft.Bot.Builder/AllowedTypesSerializationBinder.cs:line 148
>    at Microsoft.Bot.Builder.Azure.CosmosDbPartitionedStorage.WriteAsync(IDictionary`2 changes, CancellationToken cancellationToken) in /Users/runner/work/1/s/libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorage.cs:line 220
> ----- Inner Stack Trace -----
>    at Microsoft.Bot.Builder.AllowedTypesSerializationBinder.ThrowDisallowedTypesError(List`1 types) in /Users/runner/work/1/s/libraries/Microsoft.Bot.Builder/AllowedTypesSerializationBinder.cs:line 170
>    at Microsoft.Bot.Builder.AllowedTypesSerializationBinder.CleanupTypes(JContainer json) in /Users/runner/work/1/s/libraries/Microsoft.Bot.Builder/AllowedTypesSerializationBinder.cs:line 148
>    at Microsoft.Bot.Builder.Azure.CosmosDbPartitionedStorage.WriteAsync(IDictionary`2 changes, CancellationToken cancellationToken) in /Users/runner/work/1/s/libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorage.cs:line 220
> ```

@tracyboehrer, we will review them and let you know once we fix them.

Thanks!

**Comment by BruceHaley** [comment]
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.Bot.Builder.Azure.dll**

**Comment by sw-joelmut** [comment]
@tracyboehrer, we updated the failing tests to include the new custom `SerializationBinder`, and now they are all passing.

**Review by tracyboehrer — APPROVED** [review]

**Pull request merged**
